import json

more_categories = [
    # Category 10: School & Education (Cards 184-198, 15 cards)
    {
        "name": "School & Education",
        "cards": [
            {"title": "School Subjects", "words": [
                ("Math", "Mathématiques", "I love math class. - J'adore le cours de mathématiques."),
                ("Science", "Sciences", "Science lab experiment. - Expérience au laboratoire de sciences."),
                ("History", "Histoire", "History tells our story. - L'histoire raconte notre histoire."),
                ("Geography", "Géographie", "World geography map. - Carte de géographie mondiale."),
                ("Literature", "Littérature", "English literature class. - Cours de littérature anglaise."),
                ("Art", "Arts", "Art class is creative. - Le cours d'arts est créatif."),
            ]},
            {"title": "Classroom", "words": [
                ("Desk", "Bureau", "Student desk arrangement. - Arrangement des bureaux d'étudiants."),
                ("Chalkboard", "Tableau noir", "Write on chalkboard. - Écris au tableau noir."),
                ("Notebook", "Cahier", "Take notebook notes. - Prends des notes dans le cahier."),
                ("Textbook", "Manuel", "Math textbook chapter. - Chapitre du manuel de maths."),
                ("Pencil", "Crayon", "Sharpen your pencil. - Taille ton crayon."),
                ("Eraser", "Gomme", "Eraser mistakes cleanly. - Gomme les erreurs proprement."),
            ]},
            {"title": "School People", "words": [
                ("Teacher", "Professeur", "Respected teacher mentor. - Professeur mentor respecté."),
                ("Student", "Étudiant", "Diligent student effort. - Effort d'étudiant diligent."),
                ("Principal", "Directeur", "Principal office meeting. - Réunion au bureau du directeur."),
                ("Classmate", "Camarade", "Help your classmate. - Aide ta camarade de classe."),
                ("Professor", "Professeur d'université", "University professor lecture. - Cours du professeur d'université."),
                ("Tutor", "Tuteur", "Private tutor session. - Séance de tuteur privé."),
            ]},
            {"title": "Exams & Tests", "words": [
                ("Exam", "Examen", "Final exam week. - Semaine d'examens finaux."),
                ("Test", "Contrôle", "Pop quiz test. - Contrôle surprise."),
                ("Grade", "Note", "Achieved high grade. - Note élevée obtenue."),
                ("Pass", "Réussir", "Pass the exam. - Réussis l'examen."),
                ("Fail", "Échouer", "Failed the test. - A échoué le contrôle."),
                ("Cheat", "Tricher", "Don't cheat on exams. - Ne triche pas aux examens."),
            ]},
            {"title": "Learning", "words": [
                ("Study", "Étudier", "Study for finals. - Étudie pour les finals."),
                ("Learn", "Apprendre", "Learn something new. - Apprends quelque chose de nouveau."),
                ("Read", "Lire", "Read the assignment. - Lis le devoir."),
                ("Write", "Écrire", "Write an essay. - Écris une dissertation."),
                ("Practice", "Pratiquer", "Practice makes perfect. - La pratique rend parfait."),
                ("Review", "Réviser", "Review before test. - Réviser avant le contrôle."),
            ]},
            {"title": "Academic", "words": [
                ("Degree", "Diplôme", "College degree earned. - Diplôme universitaire obtenu."),
                ("Graduate", "Diplômé", "Graduate ceremony today. - Cérémonie de diplômés aujourd'hui."),
                ("Bachelor", "Licence", "Bachelor degree completion. - Completion de licence."),
                ("Scholarship", "Bourse", "Academic scholarship award. - Attribution de bourse académique."),
                ("Research", "Recherche", "Research paper project. - Projet de travail de recherche."),
                ("Thesis", "Thèse", "Master's thesis defense. - Défense de thèse de maîtrise."),
            ]},
            {"title": "School Activities", "words": [
                ("Field trip", "Sortie scolaire", "Museum field trip day. - Jour de sortie scolaire au musée."),
                ("Homework", "Devoirs", "Finish homework tonight. - Finis les devoirs ce soir."),
                ("Project", "Projet", "Group project presentation. - Présentation de projet de groupe."),
                ("Presentation", "Présentation", "Give presentation tomorrow. - Faire présentation demain."),
                ("Assignment", "Devoir", "Assignment deadline extended. - Délai de devoir prolongé."),
                ("Detention", "Retenue", "After school detention. - Retenue après l'école."),
            ]},
            {"title": "Science Terms", "words": [
                ("Experiment", "Expérience", "Chemistry experiment safety. - Sécurité d'expérience chimique."),
                ("Hypothesis", "Hypothèse", "Test the hypothesis. - Teste l'hypothèse."),
                ("Theory", "Théorie", "Scientific theory proven. - Théorie scientifique prouvée."),
                ("Formula", "Formule", "Math formula application. - Application de formule math."),
                ("Equation", "Équation", "Solve equation step by step. - Résous l'équation étape par étape."),
                ("Biology", "Biologie", "Biology cell structure. - Structure de cellule en biologie."),
            ]},
            {"title": "Languages", "words": [
                ("French", "Français", "French language fluency. - Fluidité en langue française."),
                ("Spanish", "Espagnol", "Spanish conversation practice. - Pratique de conversation espagnole."),
                ("German", "Allemand", "German grammar rules. - Règles de grammaire allemandes."),
                ("Chinese", "Chinois", "Mandarin Chinese tones. - Tons du chinois mandarin."),
                ("Japanese", "Japonais", "Japanese kanji characters. - Caractères kanji japonais."),
                ("Translation", "Traduction", "English to French translation. - Traduction anglais vers français."),
            ]},
            {"title": "Books & Reading", "words": [
                ("Library", "Bibliothèque", "School library resources. - Ressources de bibliothèque scolaire."),
                ("Publisher", "Éditeur", "Book publisher contact. - Contact d'éditeur de livre."),
                ("Bibliography", "Bibliographie", "Citation and bibliography format. - Format de citation et bibliographie."),
                ("Chapter", "Chapitre", "Read next chapter. - Lis le chapitre suivant."),
                ("Paragraph", "Paragraphe", "Write a paragraph. - Écris un paragraphe."),
                ("Summary", "Résumé", "Write story summary. - Écris le résumé de l'histoire."),
            ]},
            {"title": "School Events", "words": [
                ("Graduation", "Cérémonie de remise des diplômes", "Graduation ceremony tomorrow. - Cérémonie de remise des diplômes demain."),
                ("Assembly", "Réunion", "Morning school assembly. - Réunion matinale à l'école."),
                ("Recess", "Récréation", "Playtime at recess. - Temps de jeu à la récréation."),
                ("Semester", "Semestre", "First semester grades. - Notes du premier semestre."),
                ("Break", "Vacances", "Summer break coming. - Les vacances d'été arrivent."),
                ("Orientation", "Journée d'orientation", "New student orientation. - Journée d'orientation des nouveaux étudiants."),
            ]},
            {"title": "Art Class", "words": [
                ("Color", "Couleur", "Primary colors lesson. - Leçon sur les couleurs primaires."),
                ("Draw", "Dessiner", "Draw still life object. - Dessine un objet nature morte."),
                ("Sketch", "Esquisse", "Quick sketch practice. - Pratique d'esquisse rapide."),
                ("Clay", "Argile", "Sculpture from clay. - Sculpture en argile."),
                ("Paint", "Peindre", "Oil paint technique. - Technique de peinture à l'huile."),
                ("Craft", "Artisanat", "Art craft project. - Projet d'artisanat."),
            ]},
            {"title": "Music Class", "words": [
                ("Scale", "Gamme", "Practice music scales. - Pratique des gammes musicales."),
                ("Note", "Note", "Read music notes. - Lis les notes de musique."),
                ("Rest", "Silence", "Whole rest symbol. - Symbole de silence whole."),
                ("Staff", "Portée", "Five line music staff. - Portée de cinq lignes."),
                ("Clef", "Clé", "Treble clef reading. - Lecture de clé de sol."),
                ("Tempo", "Tempo", "Fast tempo rhythm. - Rythme de tempo rapide."),
            ]},
            {"title": "Physical Education", "words": [
                ("Gym", "Gymnase", "Gym class activities. - Activités du cours de gymnase."),
                ("Locker", "Casier", "Gym locker room. - Vestiaire avec casiers."),
                ("Uniform", "Uniforme", "Physical education uniform. - Uniforme d'éducation physique."),
                ("Warm up", "Échauffement", "Warm up exercises. - Exercices d'échauffement."),
                ("Coach", "Entraîneur", "Team sports coach. - Entraîneur d'équipes de sport."),
                ("Teamwork", "Travail d'équipe", "Good teamwork spirit. - Bon esprit de travail d'équipe."),
            ]},
        ]
    },
    # Category 11: Family & Relationships (Cards 199-213, 15 cards)
    {
        "name": "Family & Relationships",
        "cards": [
            {"title": "Immediate Family", "words": [
                ("Mother", "Mère", "Mother's Day gift. - Cadeau pour la Fête des Mères."),
                ("Father", "Père", "Father's Day surprise. - Surprise pour la Fête des Pères."),
                ("Brother", "Frère", "Older brother protection. - Protection du frère aîné."),
                ("Sister", "Sœur", "Younger sister look. - Look de petite sœur."),
                ("Son", "Fils", "Proud of my son. - Fier de mon fils."),
                ("Daughter", "Fille", "Beautiful daughter smile. - Sourire de belle fille."),
            ]},
            {"title": "Extended Family", "words": [
                ("Grandmother", "Grand-mère", "Grandmother's cooking. - Cuisine de grand-mère."),
                ("Grandfather", "Grand-père", "Grandfather's stories. - Histoires du grand-père."),
                ("Uncle", "Oncle", "Fun uncle visits. - Visites d'oncle rigolo."),
                ("Aunt", "Tante", "Aunt's birthday party. - Fête d'anniversaire de la tante."),
                ("Cousin", "Cousin", "Cousin my age. - Cousin de mon âge."),
                ("Nephew", "Neveu", "Playful nephew energy. - Énergie de neveu joueur."),
            ]},
            {"title": "In-Laws", "words": [
                ("Mother-in-law", "Belle-mère", "Mother-in-law relationship. - Relation avec la belle-mère."),
                ("Father-in-law", "Beau-père", "Father-in-law approval. - Approbation du beau-père."),
                ("Brother-in-law", "Beau-frère", "Brother-in-law introductions. - Présentations du beau-frère."),
                ("Sister-in-law", "Belle-sœur", "Sister-in-law friendship. - Amitié avec la belle-sœur."),
                ("Stepfather", "Beau-père", "Stepfather adoption. - Adoption du beau-père."),
                ("Stepbrother", "Demi-frère", "Stepbrother bonding time. - Temps de rapprochement demi-frère."),
            ]},
            {"title": "Babies & Kids", "words": [
                ("Baby", "Bébé", "Newborn baby arrival. - Arrivée du nouveau-né."),
                ("Toddler", "Enfant en bas âge", "Toddler first steps. - Premiers pas du bambin."),
                ("Child", "Enfant", "Growing child needs. - Besoins de l'enfant grandissant."),
                ("Kids", "Enfants", "Kids playground time. - Temps de jeu des enfants."),
                ("Newborn", "Nouveau-né", "Newborn baby care. - Soins du nouveau-né."),
                ("Infant", "Nourrisson", "Infant development stages. - Stades de développement du nourrisson."),
            ]},
            {"title": "Marriage", "words": [
                ("Marriage", "Mariage", "Happy marriage celebration. - Célébration de mariage heureux."),
                ("Wedding", "Noce", "Beautiful wedding ceremony. - Belle cérémonie de noces."),
                ("Spouse", "Conjoint", "Loyal spouse support. - Soutien du conjoint loyal."),
                ("Husband", "Mari", "Devoted husband love. - Amour du mari dévoué."),
                ("Wife", "Femme", "Beautiful wife appreciation. - Appréciation de la belle femme."),
                ("Anniversary", "Anniversaire de mariage", "Wedding anniversary today. - Anniversaire de mariage aujourd'hui."),
            ]},
            {"title": "Friendship", "words": [
                ("Friend", "Ami", "Best friend forever. - Meilleur ami pour toujours."),
                ("Buddy", "Camarade", "Study buddy help. - Aide du camarade d'étude."),
                ("Pal", "Copain", "Childhood pal memories. - Souvenirs du copain d'enfance."),
                ("Acquaintance", "Connaissance", "Friendly acquaintance wave. - Salut de connaissance amicale."),
                ("Roommate", "Colocataire", "College roommate situation. - Situation de colocataire universitaire."),
                ("Neighbor", "Voisin", "Help your neighbor. - Aide ton voisin."),
            ]},
            {"title": "Romantic", "words": [
                ("Boyfriend", "Petit ami", "Meet my boyfriend. - Rencontre mon petit ami."),
                ("Girlfriend", "Petite amie", "Girlfriend birthday surprise. - Surprise d'anniversaire de petite amie."),
                ("Partner", "Partenaire", "Dance partner routine. - Routine avec partenaire de danse."),
                ("Crush", "Flair", "Secret crush feelings. - Sentiments de béguin secret."),
                ("Date", "Rendez-vous galant", "First date nerves. - Nerfs de premier rendez-vous galant."),
                ("Love", "Amour", "True love story. - Histoire d'amour vraie."),
            ]},
            {"title": "Social", "words": [
                ("Group", "Groupe", "Friend group hangout. - Sortie de groupe d'amis."),
                ("Team", "Équipe", "Team spirit support. - Soutien de l'esprit d'équipe."),
                ("Club", "Club", "Join the book club. - Rejoins le club de lecture."),
                ("Organization", "Organisation", "Youth organization involvement. - Implication dans organisation jeunesse."),
                ("Community", "Communauté", "Community event volunteering. - Bénévolat d'événement communautaire."),
                ("Society", "Société", "Honor society membership. - Adhésion à la société d'honneur."),
            ]},
            {"title": "Conflict", "words": [
                ("Argument", "Dispute", "Heated argument resolved. - Dispute heated résolue."),
                ("Fight", "Combat", "Make up after fight. - Réconciliez-vous après combat."),
                ("Break up", "Rupture", "Difficult break up time. - Moment difficile de rupture."),
                ("Divorce", "Divorce", "Divorce proceedings started. - Procédures de divorce commencées."),
                ("Disagreement", "Désaccord", "Family disagreement discussion. - Discussion de désaccord familial."),
                ("Resolution", "Résolution", "Conflict resolution communication. - Communication de résolution de conflit."),
            ]},
            {"title": "Life Events", "words": [
                ("Birth", "Naissance", "Birth announcement joy. - Joie d'annonce de naissance."),
                ("Birthday", "Anniversaire", "Happy birthday wishes. - Souhaits d'anniversaire feliz."),
                ("Death", "Mort", "Funeral ceremony respect. - Respect de cérémonie funéraire."),
                ("Wedding", "Mariage", "Wedding celebration dance. - Danse de célébration de mariage."),
                ("Retirement", "Retraite", "Retirement party planning. - Planification de fête de retraite."),
                ("Reunion", "Réunion", "Family reunion gathering. - Rassemblement de réunion de famille."),
            ]},
            {"title": "Generations", "words": [
                ("Generation", "Génération", "New generation ideas. - Idées de nouvelle génération."),
                ("Ancestor", "Ancêtre", "Family ancestor roots. - Racines d'ancêtres familiaux."),
                ("Heritage", "Héritage", "Cultural heritage preservation. - Préservation de l'héritage culturel."),
                ("Tradition", "Tradition", "Family tradition continues. - La tradition familiale continue."),
                ("Legacy", "Héritage", "Leave a positive legacy. - Laisse un héritage positif."),
                ("Descendant", "Descendant", "Proud descendant pride. - Fierté de descendant."),
            ]},
            {"title": "People Descriptions", "words": [
                ("Friendly", "Amical", "Friendly person approach. - Approche de personne amicale."),
                ("Shy", "Timide", "Shy around strangers. - Timide avec les étrangers."),
                ("Outgoing", "Extraverti", "Outgoing personality shine. - Brillance de personnalité extravertie."),
                ("Loyal", "Loyal", "Loyal friend support. - Soutien d'ami loyal."),
                ("Honest", "Honnête", "Honest answer always. - Réponse honnête toujours."),
                ("Generous", "Généreux", "Generous heart giving. - Don généreux du cœur."),
            ]},
            {"title": "Emotions & Feelings", "words": [
                ("Happy", "Heureux", "Happy memories together. - Souvenirs heureux ensemble."),
                ("Sad", "Triste", "Sad movie tears. - Larmes de film triste."),
                ("Angry", "En colère", "Calm down angry feelings. - Calme les sentiments en colère."),
                ("Excited", "Excité", "Excited anticipation grows. - L'anticipation excitee grandit."),
                ("Nervous", "Nerveux", "Nervous before presentation. - Nerveux avant présentation."),
                ("Grateful", "Reconnaissant", "Grateful for everything. - Reconnaissant pour tout."),
            ]},
            {"title": "Trust & Betrayal", "words": [
                ("Trust", "Confiance", "Build trust slowly. - Construis la confiance lentement."),
                ("Betray", "Trahir", "Never betray friends. - Ne trahis jamais les amis."),
                ("Loyal", "Fidèle", "Loyal until the end. - Fidèle jusqu'à la fin."),
                ("Honesty", "Honnêteté", "Honesty is important. - L'honnêteté est importante."),
                ("Promise", "Promesse", "Keep your promise. - Garde ta promesse."),
                ("Secret", "Secret", "Keep a secret safe. - Garde un secret en sécurité."),
            ]},
            {"title": "Getting to Know", "words": [
                ("Introduce", "Présenter", "Introduce yourself please. - Présente-toi s'il te plaît."),
                ("Meet", "Rencontrer", "Nice to meet you. - Enchanté de te rencontrer."),
                ("Remember", "Se souvenir", "Remember my name. - Souviens-toi de mon nom."),
                ("Understand", "Comprendre", "Understand each other. - Comprenons-nous mutuellement."),
                ("Accept", "Accepter", "Accept differences kindly. - Accepte les différences gentiment."),
                ("Respect", "Respecter", "Respect everyone equally. - Respecte tout le monde également."),
            ]},
        ]
    },
    # Category 12: Places & Buildings (Cards 214-228, 15 cards)
    {
        "name": "Places & Buildings",
        "cards": [
            {"title": "City Places", "words": [
                ("City", "Ville", "Big city lights. - Lumières de grande ville."),
                ("Downtown", "Centre-ville", "Downtown business district. - Quartier des affaires du centre-ville."),
                ("Suburb", "Banlieue", "Quiet suburb living. - Vie tranquille en banlieue."),
                ("Avenue", "Avenue", "Main avenue shopping. - Shopping sur l'avenue principale."),
                ("Street", "Rue", "Maple street name. - Nom de rue de l'Érable."),
                ("Block", "Îlot", "City block walk. - Marche d'îlot urbain."),
            ]},
            {"title": "Buildings", "words": [
                ("Building", "Immeuble", "Tall building architecture. - Architecture d'immeuble haut."),
                ("Tower", "Tour", "Office tower view. - Vue de tour de bureau."),
                ("Skyscraper", "Gratte-ciel", "City skyline skyscraper. - Gratte-ciel de ligne d'horizon."),
                ("House", "Maison", "Home sweet house. - Maison douce maison."),
                ("Apartment", "Appartement", "Apartment on third floor. - Appartement au troisième étage."),
                ("Mansion", "Manoir", "Historic mansion tour. - Visite de manoir historique."),
            ]},
            {"title": "Rooms", "words": [
                ("Kitchen", "Cuisine", "Modern kitchen design. - Design de cuisine moderne."),
                ("Bedroom", "Chambre", "Cozy bedroom setup. - Aménagement de chambre cozy."),
                ("Bathroom", "Salle de bain", "Bathroom renovation project. - Projet de rénovation de salle de bain."),
                ("Living room", "Salon", "Family living room gathering. - Rassemblement familial au salon."),
                ("Dining room", "Salle à manger", "Dining room table setting. - Dressage de table de salle à manger."),
                ("Basement", "Sous-sol", "Finished basement space. - Espace de sous-sol fini."),
            ]},
            {"title": "Stores", "words": [
                ("Supermarket", "Supermarché", "Weekly supermarket trip. - Course hebdomadaire au supermarché."),
                ("Clothing store", "Magasin de vêtements", "New clothing store opened. - Nouveau magasin de vêtements ouvert."),
                ("Bookstore", "Librairie", "Browse the bookstore. - Parcours la librairie."),
                ("Pharmacy", "Pharmacie", "Pick up prescription at pharmacy. - Récupère l'recette à la pharmacie."),
                ("Bakery", "Boulangerie", "Fresh bakery bread. - Pain frais de boulangerie."),
                ("Mall", "Centre commercial", "Mall shopping day. - Jour de shopping au centre commercial."),
            ]},
            {"title": "Public Buildings", "words": [
                ("Library", "Bibliothèque", "Public library resources. - Ressources de bibliothèque publique."),
                ("Museum", "Musée", "Art museum visit. - Visite de musée d'art."),
                ("Hospital", "Hôpital", "Visit friend at hospital. - Visite ami à l'hôpital."),
                ("Church", "Église", "Sunday church service. - Messe d'église de dimanche."),
                ("City hall", "Hôtel de ville", "City hall meeting. - Réunion à l'hôtel de ville."),
                ("Post office", "Bureau de poste", "Mail at post office. - Courrier au bureau de poste."),
            ]},
            {"title": "Outdoor Places", "words": [
                ("Park", "Parc", "Central park picnic. - Pique-nique au parc central."),
                ("Garden", "Jardin", "Community garden plot. - Parcelle de jardin communautaire."),
                ("Playground", "Terrain de jeu", "Kids playground equipment. - Équipement de terrain de jeu."),
                ("Pool", "Piscine", "Public swimming pool. - Piscine publique."),
                ("Stadium", "Stade", "Sports stadium event. - Événement au stade sportif."),
                ("Zoo", "Zoo", "Family zoo trip. - Sortie zoo en famille."),
            ]},
            {"title": "Water Places", "words": [
                ("Beach", "Plage", "Sandy beach vacation. - Vacances à la plage sablonneuse."),
                ("Lake", "Lac", "Lake house retreat. - Retraite à la maison du lac."),
                ("River", "Rivière", "River boat cruise. - Croisière en bateau sur la rivière."),
                ("Ocean", "Océan", "Pacific ocean waves. - Vagues de l'océan Pacifique."),
                ("Pond", "Étang", "Duck pond feeding. - Alimentation des canards à l'étang."),
                ("Waterfall", "Cascade", "Beautiful waterfall hike. - Randonnée à la belle cascade."),
            ]},
            {"title": "Landmarks", "words": [
                ("Bridge", "Pont", "Golden Gate Bridge view. - Vue du pont du Golden Gate."),
                ("Tower", "Tour", "Eiffel Tower visit. - Visite de la Tour Eiffel."),
                ("Monument", "Monument", "Historical monument honored. - Monument historique honoré."),
                ("Castle", "Château", "Medieval castle tour. - Visite de château médiéval."),
                ("Palace", "Palais", "Royal palace gardens. - Jardins du palais royal."),
                ("Cathedral", "Cathédrale", "Gothic cathedral architecture. - Architecture de cathédrale gothique."),
            ]},
            {"title": "Travel Places", "words": [
                ("Hotel", "Hôtel", "Luxury hotel suite. - Suite d'hôtel de luxe."),
                ("Motel", "Motel", "Roadside motel stay. - Séjour au motel sur route."),
                ("Hostel", "Auberge", "Budget hostel booking. - Réservation d'auberge économique."),
                ("Resort", "Station", "Beach resort vacation. - Vacances à la station balnéaire."),
                ("Campsite", "Camping", "Mountain campsite spot. - Emplacement de camping en montagne."),
                ("Lodge", "Chalet", "Forest lodge getaway. - Évasion au chalet en forêt."),
            ]},
            {"title": "Workplaces", "words": [
                ("Office", "Bureau", "Corporate office building. - Immeuble de bureau d'entreprise."),
                ("Factory", "Usine", "Car factory production. - Production d'usine de voiture."),
                ("Store", "Magasin", "Retail store hours. - Heures d'ouverture du magasin."),
                ("Restaurant", "Restaurant", "Popular restaurant review. - Critique de restaurant populaire."),
                ("Cafe", "Café", "Corner cafe coffee. - Café du coin."),
                ("Bar", "Bar", "Sports bar TV. - TV de bar sportif."),
            ]},
            {"title": "Educational", "words": [
                ("School", "École", "Elementary school yard. - Cour d'école primaire."),
                ("College", "Collège", "Community college course. - Cours de collège communautaire."),
                ("University", "Université", "Large university campus. - Grand campus universitaire."),
                ("Library", "Bibliothèque", "University library study. - Étude à la bibliothèque universitaire."),
                ("Laboratory", "Laboratoire", "Science laboratory equipment. - Équipement de laboratoire scientifique."),
                ("Campus", "Campus", "Beautiful campus grounds. - Beaux terrains de campus."),
            ]},
            {"title": "Nature Areas", "words": [
                ("Forest", "Forêt", "Dense forest hiking. - Randonnée en forêt dense."),
                ("Mountain", "Montagne", "Mountain peak climbing. - Ascension de pic de montagne."),
                ("Valley", "Vallée", "Green valley view. - Vue de vallée verte."),
                ("Canyon", "Canyon", "Grand canyon exploration. - Exploration du grand canyon."),
                ("Desert", "Désert", "Hot desert landscape. - Paysage de désert chaud."),
                ("Island", "Île", "Tropical island paradise. - Paradis d'île tropicale."),
            ]},
            {"title": "Neighborhood", "words": [
                ("Neighborhood", "Quartier", "Quiet neighborhood streets. - Rues de quartier tranquilles."),
                ("Corner", "Coin", "Corner store run. - Course au magasin du coin."),
                ("Block", "Bloc", "Whole block party. - Fête de tout le bloc."),
                ("District", "Secteur", "Business district area. - Zone du secteur des affaires."),
                ("Sidewalk", "Trottoir", "Sidewalk cafes line. - Rangée de cafes sidewalk."),
                ("Crosswalk", "Passage piéton", "Crosswalk safety rules. - Règles de sécurité passage piéton."),
            ]},
            {"title": "Entertainment", "words": [
                ("Cinema", "Cinéma", "New cinema release. - Nouvelle sortie au cinéma."),
                ("Theater", "Théâtre", "Broadway theater show. - Spectacle de théâtre Broadway."),
                ("Concert hall", "Salle de concert", "Concert hall acoustics. - Acoustique de salle de concert."),
                ("Arcade", "Salle d'arcade", "Retro arcade games. - Jeux d'arcade rétro."),
                ("Amusement park", "Parc d'attractions", "Roller coaster at amusement park. - Montagnes russes au parc d'attractions."),
                ("Zoo", "Zoo", "Zoo animal exhibits. - Expositions d'animaux du zoo."),
            ]},
            {"title": "Service Places", "words": [
                ("Bank", "Banque", "Bank ATM withdrawal. - Retrait au DAB de la banque."),
                ("Gas station", "Station-service", "Gas station fill up. - Faire le plein à la station-service."),
                ("Repair shop", "Atelier de réparation", "Bike repair shop help. - Aide d'atelier de réparation de vélo."),
                ("Dry cleaner", "Pressing", "Pick up dry cleaning. - Récupère le pressing."),
                ("Barbershop", "Coiffeur", "Barbershop haircut style. - Style de coupe au barbier."),
                ("Salon", "Salon de beauté", "Beauty salon appointment. - Rendez-vous au salon de beauté."),
            ]},
        ]
    },
    # Category 13: Professions & Jobs (Cards 229-243, 15 cards)
    {
        "name": "Professions & Jobs",
        "cards": [
            {"title": "Medical Jobs", "words": [
                ("Doctor", "Médecin", "Family doctor appointment. - Rendez-vous chez le médecin de famille."),
                ("Nurse", "Infirmier", "Nurse caring dedication. - Dévouement soignant de l'infirmier."),
                ("Surgeon", "Chirurgien", "Skilled surgeon hands. - Mains expertes du chirurgien."),
                ("Dentist", "Dentiste", "Regular dentist checkup. - Contrôle régulier chez le dentiste."),
                ("Pharmacist", "Pharmacien", "Pharmacist advice helpful. - Conseil utile du pharmacien."),
                ("Therapist", "Thérapeute", "Mental health therapist. - Thérapeute de santé mentale."),
            ]},
            {"title": "Education Jobs", "words": [
                ("Teacher", "Professeur", "Elementary school teacher. - Professeur d'école primaire."),
                ("Professor", "Professeur d'université", "University professor research. - Recherche du professeur d'université."),
                ("Tutor", "Tuteur", "Math tutor sessions. - Séances de tuteur de maths."),
                ("Principal", "Directeur", "School principal leadership. - Leadership du directeur d'école."),
                ("Librarian", "Bibliothécaire", "Helpful librarian assistance. - Assistance utile du bibliothécaire."),
                ("Counselor", "Conseiller", "School counselor advice. - Conseil du conseiller scolaire."),
            ]},
            {"title": "Business Jobs", "words": [
                ("Manager", "Directeur", "Store manager schedule. - Horaire du directeur de magasin."),
                ("Accountant", "Comptable", "Tax accountant help. - Aide du comptable fiscal."),
                ("Receptionist", "Réceptionniste", "Hotel receptionist greeting. - Salutation de réceptionniste d'hôtel."),
                ("Secretary", "Secrétaire", "Office secretary tasks. - Tâches de secrétaire de bureau."),
                ("Consultant", "Consultant", "Business consultant advice. - Conseil de consultant d'affaires."),
                ("Executive", "Exécutif", "Company executive meeting. - Réunion d'exécutif d'entreprise."),
            ]},
            {"title": "Tech Jobs", "words": [
                ("Programmer", "Programmeur", "Software programmer coding. - Codage de programmeur logiciel."),
                ("Designer", "Designer", "Graphic designer portfolio. - Portfolio de designer graphique."),
                ("Engineer", "Ingénieur", "Engineer problem solving. - Résolution de problèmes d'ingénieur."),
                ("Technician", "Technicien", "IT technician support. - Support du technicien informatique."),
                ("Developer", "Développeur", "App developer creating. - Création de développeur d'applications."),
                ("Analyst", "Analyste", "Data analyst insights. - Aperçus de l'analyste de données."),
            ]},
            {"title": "Service Jobs", "words": [
                ("Server", "Serveur", "Restaurant server tips. - Pourboires du serveur de restaurant."),
                ("Cashier", "Caissier", "Friendly cashier interaction. - Interaction amicale du caissier."),
                ("Bartender", "Barman", "Mixology bartender skills. - Compétences de mixologie du barman."),
                ("Chef", "Chef", "Executive chef creations. - Créations du chef exécutif."),
                ("Janitor", "Concierge", "Building janitor duties. - Devoirs du concierge d'immeuble."),
                ("Mechanic", "Mécanicien", "Auto mechanic expertise. - Expertise du mécanicien auto."),
            ]},
            {"title": "Creative Jobs", "words": [
                ("Artist", "Artiste", "Visual artist gallery. - Galerie d'artista visuel."),
                ("Musician", "Musicien", "Professional musician performance. - Performance de musicienne professionnelle."),
                ("Photographer", "Photographe", "Wedding photographer coverage. - Couverture du photographe de mariage."),
                ("Writer", "Écrivain", "Novel writer creative process. - Processus créatif de l'écrivaine de roman."),
                ("Actor", "Acteur", "Film actor career. - Carrière d'acteur de film."),
                ("Journalist", "Journaliste", "News journalist reporting. - Rapportage du journaliste d'actualités."),
            ]},
            {"title": "Legal & Government", "words": [
                ("Lawyer", "Avocat", "Defense lawyer skills. - Compétences de l'avocate de la défense."),
                ("Judge", "Juge", "Judge courtroom decision. - Décision de salle d'audience du juge."),
                ("Police officer", "Agent de police", "Police officer duty. - Devoir de l'agent de police."),
                ("Firefighter", "Pompier", "Brave firefighter rescue. - Sauvetage courageux du pompier."),
                ("Soldier", "Soldat", "Military soldier training. - Entraînement du soldat militaire."),
                ("Politician", "Homme politique", "Local politician campaign. - Campagne de l'homme politique local."),
            ]},
            {"title": "Sports & Fitness", "words": [
                ("Athlete", "Athlète", "Professional athlete dedication. - Dévouement d'athlète professionnel."),
                ("Coach", "Entraîneur", "Team sports coach. - Entraîneur d'équipes de sport."),
                ("Trainer", "Formateur", "Personal trainer sessions. - Séances de formatrice personnelle."),
                ("Referee", "Arbitre", "Fair referee decisions. - Décisions justes de l'arbitre."),
                ("Trainer", "Dresseur", "Animal trainer skills. - Compétences du dresseur d'animaux."),
                (" lifeguard", "Maître-nageur", "Pool lifeguard vigilance. - Vigilance du maître-nageur."),
            ]},
            {"title": "Trades", "words": [
                ("Carpenter", "Charpentier", "Skilled carpenter craftsmanship. - Artisanat du charpentier qualifié."),
                ("Electrician", "Électricien", "Licensed electrician work. - Travail d'électricien autorisé."),
                ("Plumber", "Plombier", "Emergency plumber call. - Appel d'urgence du plombier."),
                ("Painter", "Peintre", "House painter color choices. - Choix de couleur du peintre de maison."),
                ("Roofer", "Couvreur", "Professional roofer repair. - Réparation de couvreur professionnel."),
                ("Landscaper", "Paysagiste", "Garden landscaper design. - Design du paysagiste de jardin."),
            ]},
            {"title": "Science Jobs", "words": [
                ("Scientist", "Scientifique", "Research scientist discovery. - Découverte du chercheur scientifique."),
                ("Biologist", "Biologist", "Marine biologist studies. - Études du biologiste marin."),
                ("Chemist", "Chimiste", "Chemistry lab chemist. - Chimiste de laboratoire de chimie."),
                ("Physicist", "Physicien", "Particle physicist research. - Recherche du physicien des particules."),
                ("Astronomer", "Astronome", "Telescope astronomer watching. - Observation de l'astronome avec télescope."),
                ("Geologist", "Géologue", "Field geologist exploration. - Exploration du géologue de terrain."),
            ]},
            {"title": "Media & Communication", "words": [
                ("Reporter", "Reporter", "News reporter live. - Reportage du reporter d'actualités en direct."),
                ("Producer", "Producteur", "Film producer funding. - Financement du producteur de film."),
                ("Director", "Réalisateur", "Movie director vision. - Vision du réalisateur de film."),
                ("Editor", "Éditeur", "News editor decisions. - Décisions de l'éditeur de nouvelles."),
                ("Blogger", "Blogueur", "Popular blogger posts. - Publications duBlogueur populaire."),
                ("Influencer", "Influenceur", "Social media influencer. - Influenceur des réseaux sociaux."),
            ]},
            {"title": "Agriculture", "words": [
                ("Farmer", "Agriculteur", "Family farmer harvest. - Récolte de l'agriculteur familial."),
                ("Gardener", "Jardinier", "Professional gardener services. - Services du jardinier professionnel."),
                ("Breeder", "Éleveur", "Animal breeder expertise. - Expertise de l'éleveur d'animaux."),
                ("Veterinarian", "Vétérinaire", "Pet veterinarian care. - Soins du télévisionniste."),
                ("Florist", "Fleuriste", "Fresh florist arrangements. - Arrangements du fleuriste frais."),
                ("Beekeeper", "Apiculteur", "Local beekeeper honey. - Miel de l'apiculteur local."),
            ]},
            {"title": "Transportation", "words": [
                ("Driver", "Chauffeur", "Professional driver license. - Permis de chauffeur professionnel."),
                ("Pilot", "Pilote", "Airline pilot career. - Carrière de pilote de ligne."),
                ("Captain", "Capitaine", "Ship captain command. - Commande du capitaine de navire."),
                ("Conductor", "Contrôleur", "Train conductor duties. - Devoirs du contrôleur de train."),
                ("Delivery person", "Livreur", "Package delivery person. - Livreur de colis."),
                ("Garbage collector", "Éboueur", "Municipal garbage collector. - Éboueur municipal."),
            ]},
            {"title": "Hospitality", "words": [
                ("Hotel manager", "Directeur d'hôtel", "Hotel manager responsibilities. - Responsabilités du directeur d'hôtel."),
                ("Concierge", "Concierge", "Hotel concierge recommendations. - Recommandations du concierge d'hôtel."),
                ("Housekeeper", "Femme de ménage", "Efficient housekeeper skills. - Compétences efficaces de la femme de ménage."),
                ("Tour guide", "Guide touristique", "Local tour guide expertise. - Expertise du guide touristique local."),
                ("Flight attendant", "Hôtesse de l'air", "Flight attendant safety demo. - Démonstration de sécurité de l'hôtesse de l'air."),
                ("Cruise director", "Directeur de croisière", "Entertainment cruise director. - Divertissement du directeur de croisière."),
            ]},
            {"title": "Jobs & Work", "words": [
                ("Job", "Emploi", "Find a new job. - Trouve un nouvel emploi."),
                ("Career", "Carrière", "Career development path. - Chemin de développement de carrière."),
                ("Salary", "Salaire", "Competitive salary offer. - Offre de salaire compétitif."),
                ("Promotion", "Promotion", "Well deserved promotion. - Promotion méritée."),
                ("Resignation", "Démission", "Resignation letter writing. - Rédaction de lettre de démission."),
                ("Unemployment", "Chômage", "Unemployment benefits application. - Demande d'allocation de chômage."),
            ]},
        ]
    },
    # Category 14: Additional Categories to reach 250 (Cards 244-250 = 7 cards needed)
    {
        "name": "Space & Astronomy",
        "cards": [
            {"title": "Space Objects", "words": [
                ("Star", "Étoile", "Bright star shining. - Étoile brillante luisante."),
                ("Planet", "Planète", "Eight planets orbit. - Huit planètes en orbite."),
                ("Moon", "Lune", "Full moon tonight. - Lune pleine ce soir."),
                ("Sun", "Soleil", "Sunrise and sunset. - Lever et coucher du soleil."),
                ("Galaxy", "Galaxie", "Milky Way galaxy. - Galaxie de la Voie lactée."),
                ("Universe", "Univers", "Expanding universe theory. - Théorie de l'univers en expansion."),
            ]},
            {"title": "Space Exploration", "words": [
                ("Astronaut", "Astronaute", "International Space Station astronaut. - Astronaute de Station spatiale internationale."),
                ("Rocket", "Fusée", "Space rocket launch. - Lancement de fusée spatiale."),
                ("Satellite", "Satellite", "Communication satellite orbit. - Orbite de satellite de communication."),
                ("Spacecraft", "Vaisseau spatial", "Robotic spacecraft exploration. - Exploration par vaisseau spatial robotique."),
                ("Mission", "Mission", "Mars mission planning. - Planification de mission vers Mars."),
                ("Spacewalk", "Sortie spatiale", "Astronaut spacewalk outside. - Sortie spatiale de l'astronaute à l'extérieur."),
            ]},
            {"title": "Social Issues", "words": [
                ("Poverty", "Pauvreté", "Fight against poverty. - Lutte contre la pauvreté."),
                ("Inequality", "Inégalités", "Social inequality awareness. - Sensibilisation aux inégalités sociales."),
                ("Discrimination", "Discrimination", "Zero discrimination policy. - Politique de tolérance zéro pour la discrimination."),
                ("Human rights", "Droits de l'homme", "Defend human rights. - Défends les droits de l'homme."),
                ("Climate change", "Changement climatique", "Climate change action needed. - Action contre le changement climatique nécessaire."),
                ("Sustainability", "Durabilité", "Practice sustainability daily. - Pratique la durabilité quotidiennement."),
            ]},
            {"title": "Philosophy", "words": [
                ("Ethics", "Éthique", "Medical ethics committee. - Comité d'éthique médicale."),
                ("Logic", "Logique", "Philosophical logic reasoning. - Raisonnement de logique philosophique."),
                ("Metaphysics", "Métaphysique", "Study of metaphysics. - Étude de la métaphysique."),
                ("Epistemology", "Épistémologie", "Branch of epistemology. - Branche de l'épistémologie."),
                ("Existentialism", "Existentialisme", "Philosophy of existentialism. - Philosophie de l'existentialisme."),
                ("Rationality", "Rationalité", "Human rationality limit. - Limite de la rationalité humaine."),
            ]},
            {"title": "Architecture", "words": [
                ("Architect", "Architecte", "Famous architect design. - Design d'architecte célèbre."),
                ("Blueprint", "Plan", "Read blueprint accurately. - Lis le plan avec précision."),
                ("Foundation", "Fondation", "Building foundation concrete. - Béton de fondation du bâtiment."),
                ("Skyscraper", "Gratte-ciel", "City skyscraper silhouette. - Silhouette du gratte-ciel de la ville."),
                ("Monument", "Monument", "Historic monument preservation. - Préservation du monument historique."),
                ("Renovation", "Rénovation", "Home renovation project. - Projet de rénovation domiciliaire."),
            ]},
            {"title": "Music & Musicians", "words": [
                ("Composer", "Compositeur", "Famous composer symphony. - Symphonie du compositeur célèbre."),
                ("Conductor", "Chef d'orchestre", "Orchestra conductor gesture. - Geste du chef d'orchestre."),
                ("Symphony", "Symphonie", "Beethoven symphony performance. - Performance de symphonie de Beethoven."),
                ("Melody", "Mélodie", "Beautiful melody harmony. - Harmonie de belle mélodie."),
                ("Rhythm", "Rythme", "Dance to the rhythm. - Danse sur le rythme."),
                ("Chord", "Accord", "Guitar chord progression. - Progression d'accords de guitare."),
            ]},
            {"title": "Photography", "words": [
                ("Camera", "Appareil photo", "Professional camera lens. - Objectif d'appareil photo professionnel."),
                ("Portrait", "Portrait", "Family portrait session. - Séance de portrait de famille."),
                ("Landscape", "Paysage", "Mountain landscape scenery. - Scène de paysage de montagne."),
                ("Selfie", "Selfie", "Take a selfie. - Prends un selfie."),
                ("Focus", "Mise au point", "Adjust camera focus. - Ajuste la mise au point de l'appareil."),
                ("Flash", "Flash", "Camera flash brightness. - Luminosité du flash de l'appareil."),
            ]},
            {"title": "Fashion", "words": [
                ("Designer", "Designer", "Fashion designer collection. - Collection de designer de mode."),
                ("Runway", "Podium", "Fashion runway show. - Défilé de mode sur le podium."),
                ("Vintage", "Vintage", "Vintage clothing store. - Magasin de vêtements vintage."),
                ("Accessory", "Accessoire", "Fashion accessory choice. - Choix d'accessoire de mode."),
                ("Tailor", "Tailleur", "Custom tailor suit. - Costume sur mesure du tailleur."),
                (" Boutique", "Boutique", "Luxury boutique shopping. - Shopping de boutique de luxe."),
            ]},
        ]
    },
]

# Current highest card is 183, so start from 184
card_number = 184

for category in more_categories:
    for card_template in category["cards"]:
        if card_number > 250:
            break
        card_id = f"w{card_number:05d}"
        card = {
            "id": card_id,
            "title": card_template["title"],
            "day": card_number,
            "words": []
        }
        for i, (english, french, example) in enumerate(card_template["words"], 1):
            card["words"].append({
                "id": i,
                "english": english,
                "french": french,
                "example": example
            })
        
        with open(f"src/lib/data/{card['id']}.json", "w") as f:
            json.dump(card, f, indent=2, ensure_ascii=False)
        
        card_number += 1
        if card_number > 250:
            break
    if card_number > 250:
        break

print(f"Generated cards up to w{card_number-1:05d}")
