import json
import os

vocab_categories = [
    # Category 1: Sports & Activities (Cards 51-60, 10 cards)
    {
        "name": "Sports & Activities",
        "cards": [
            {"title": "Team Sports", "words": [
                ("Football", "Football", "I play football every Saturday. - Je joue au football chaque samedi."),
                ("Basketball", "Basketball", "Basketball is very popular. - Le basketball est très populaire."),
                ("Volleyball", "Volleyball", "We won the volleyball match! - Nous avons gagné le match de volley!"),
                ("Rugby", "Rugby", "Rugby is a rough sport. - Le rugby est un sport violent."),
                ("Handball", "Handball", "I joined the handball team. - J'ai rejoint l'équipe de handball."),
                ("Baseball", "Baseball", "Baseball is America's pastime. - Le baseball est le passe-temps américain."),
            ]},
            {"title": "Individual Sports", "words": [
                ("Tennis", "Tennis", "She is a tennis champion. - Elle est championne de tennis."),
                ("Swimming", "Natation", "Swimming is great exercise. - La natation est un excellent exercice."),
                ("Cycling", "Cyclisme", "We went cycling in the mountains. - Nous avons fait du vélo dans les montagnes."),
                ("Athletics", "Athlétisme", "Track athletics includes running. - L'athlétisme sur piste comprend la course."),
                ("Gymnastics", "Gymnastique", "She does gymnastics every week. - Elle fait de la gymnastique chaque semaine."),
                ("Boxing", "Boxe", "Boxing requires a lot of training. - La boxe demande beaucoup d'entraînement."),
            ]},
            {"title": "Outdoor Activities", "words": [
                ("Hiking", "Randonnée", "Hiking in the Alps is amazing. - La randonnée dans les Alpes est incroyable."),
                ("Camping", "Camping", "We did camping last summer. - Nous avons fait du camping l'été dernier."),
                ("Climbing", "Escalade", "Climbing needs courage. - L'escalade demande du courage."),
                ("Surfing", "Surf", "The waves are perfect for surfing. - Les vagues sont parfaites pour le surf."),
                ("Skiing", "Ski", "We go skiing in winter. - Nous allons skier en hiver."),
                ("Skateboarding", "Skateboard", "He learned skateboarding tricks. - Il a appris des tricks en skateboard."),
            ]},
            {"title": "Water Sports", "words": [
                ("Diving", "Plongée", "Scuba diving is fascinating. - La plongée sous-marine est fascinante."),
                ("Kayaking", "Canoë-kayak", "We went kayaking on the river. - Nous avons fait du canoe-kayak sur la rivière."),
                ("Sailing", "Voile", "Sailing requires wind. - La voile nécessite du vent."),
                ("Rowing", "Aviron", "He practices rowing every morning. - Il pratique l'aviron chaque matin."),
                ("Windsurfing", "Planche à voile", "Windsurfing combines sailing and surfing. - La planche à voile combine la voile et le surf."),
                ("Snorkeling", "Snorkeling", "Snorkeling lets you see fish. - Le snorkeling permet de voir les poissons."),
            ]},
            {"title": "Fitness & Exercise", "words": [
                ("Running", "Course", "Morning running keeps me fit. - La course du matin me garde en forme."),
                ("Yoga", "Yoga", "Yoga helps me relax. - Le yoga m'aide à me détendre."),
                ("Pilates", "Pilates", "Pilates strengthens your core. - Le Pilates renforce votre centre."),
                ("Weightlifting", "Haltérophilie", "He does weightlifting at the gym. - Il fait de l'haltérophilie à la salle."),
                ("Stretching", "Étirements", "Stretching prevents injuries. - Les étirements préviennent les blessures."),
                ("Dancing", "Danse", "Dancing is so much fun! - La danse est tellement amusante!"),
            ]},
            {"title": "Ball Games", "words": [
                ("Soccer", "Football", "My favorite soccer team won! - Mon équipe de football préférée a gagné!"),
                ("Golf", "Golf", "We played golf on Sunday. - Nous avons joué au golf dimanche."),
                ("Table tennis", "Tennis de table", "Table tennis is fast. - Le tennis de table est rapide."),
                ("Badminton", "Badminton", "Badminton is played with rackets. - Le badminton se joue avec des raquettes."),
                ("Bowling", "Bowling", "Let's go bowling! - Allons au bowling!"),
                ("Billiards", "Billard", "He plays billiards at the club. - Il joue au billard au club."),
            ]},
            {"title": "Winter Sports", "words": [
                ("Ice skating", "Patinage", "Ice skating is magical. - Le patinage est magique."),
                ("Ice hockey", "Hockey sur glace", "Ice hockey is exciting to watch. - Le hockey sur glace est激动人心."),
                ("Sledding", "Luge", "The kids love sledding. - Les enfants adorent la luge."),
                ("Curling", "Curling", "Curling is a strategic sport. - Le curling est un sport stratégique."),
                ("Bobsleigh", "Bobsleigh", "Bobsleigh is an Olympic sport. - Le bobsleigh est un sport Olympique."),
                ("Snowboarding", "Snowboard", "Snowboarding looks cool. - Le snowboard a l'air cool."),
            ]},
            {"title": "Extreme Sports", "words": [
                ("Skydiving", "Parachutisme", "Skydiving is terrifying! - Le parachutisme est terrifiant!"),
                ("Bungee jumping", "Saut à l'élastique", "Bungee jumping is so scary! - Le saut à l'élastique est si effrayant!"),
                ("Paragliding", "Parapente", "Paragliding offers amazing views. - Le parapente offre des vues incroyables."),
                ("Rafting", "Rafting", "White water rafting is adventure! - Le rafting en eau vive est une aventure!"),
                ("BMX", "BMX", "He performs BMX tricks. - Il effectue des tricks en BMX."),
                ("Motocross", "Motocross", "Motocross races are loud. - Les courses de motocross sont bruyantes."),
            ]},
            {"title": "Mind Sports", "words": [
                ("Chess", "Échecs", "Chess improves thinking. - Les échecs améliorent la réflexion."),
                ("Chess player", "Joueur d'échecs", "She is a chess grandmaster. - Elle est grand maître d'échecs."),
                ("Card games", "Jeux de cartes", "We play card games at night. - Nous jouons aux cartes le soir."),
                ("Poker", "Poker", "Poker is a game of strategy. - Le poker est un jeu de stratégie."),
                ("Chess tournament", "Tournoi d'échecs", "The chess tournament starts Monday. - Le tournoi d'échecs commence lundi."),
                ("Strategy game", "Jeu de stratégie", "I love strategy games. - J'adore les jeux de stratégie."),
            ]},
            {"title": "Spectator Sports", "words": [
                ("Stadium", "Stade", "The stadium was full. - Le stade était plein."),
                ("Championship", "Championnat", "The world championship is here. - Le championnat du monde est ici."),
                ("Score", "Score", "What's the score? - Quel est le score?"),
                ("Fans", "Fans", "The fans were cheering. - Les fans acclamient."),
                ("Referee", "Arbitre", "The referee made a call. - L'arbitre a pris une décision."),
                ("Trophy", "Trophée", "They won the trophy! - Ils ont gagné le trophée!"),
            ]},
        ]
    },
    # Category 2: Animals & Nature (Cards 61-75, 15 cards)
    {
        "name": "Animals & Nature",
        "cards": [
            {"title": "Farm Animals", "words": [
                ("Cow", "Vache", "The cow produces milk. - La vache produit du lait."),
                ("Pig", "Cochon", "The pig is eating. - Le cochon mange."),
                ("Sheep", "Mouton", "The sheep have wool. - Les moutons ont de la laine."),
                ("Horse", "Cheval", "I ride a horse. - Je monte à cheval."),
                ("Chicken", "Poule", "The chicken lays eggs. - La poule pond des œufs."),
                ("Rooster", "Coq", "The rooster crows. - Le coq chante."),
            ]},
            {"title": "Wild Animals", "words": [
                ("Lion", "Lion", "The lion is the king. - Le lion est le roi."),
                ("Elephant", "Élphant", "An elephant never forgets. - Un éléphant n'oublie jamais."),
                ("Monkey", "Singe", "The monkey swings in trees. - Le singe se balance dans les arbres."),
                ("Giraffe", "Girafe", "The giraffe has a long neck. - La girafe a un long cou."),
                ("Zebra", "Zèbre", "Zebras are striped. - Les zèbres sont rayés."),
                ("Kangaroo", "Kangourou", "The kangaroo hops. - Le kangourou saute."),
            ]},
            {"title": "Pets", "words": [
                ("Dog", "Chien", "My dog is friendly. - Mon chien est gentil."),
                ("Cat", "Chat", "The cat sleeps a lot. - Le chat dort beaucoup."),
                ("Goldfish", "Poisson rouge", "The goldfish is orange. - Le poisson rouge est orange."),
                ("Hamster", "Hamster", "The hamster runs on its wheel. - Le hamster court sur sa roue."),
                ("Parrot", "Perroquet", "The parrot talks. - Le perroquet parle."),
                ("Rabbit", "Lapin", "The rabbit hops in the garden. - Le lapin saute dans le jardin."),
            ]},
            {"title": "Birds", "words": [
                ("Eagle", "Aigle", "The eagle soars. - L'aigle plane."),
                ("Owl", "Hibou", "The owl hunts at night. - Le hibou chasse la nuit."),
                ("Penguin", "Manchot", "Penguins live in cold places. - Les manchots vivent dans des endroits froids."),
                ("Sparrow", "Moineau", "The sparrow sings. - Le moineau chante."),
                ("Flamingo", "Flamant", "The flamingo is pink. - Le flamant est rose."),
                ("Peacock", "Paon", "The peacock displays its feathers. - Le paon display ses plumes."),
            ]},
            {"title": "Sea Animals", "words": [
                ("Dolphin", "Dauphin", "Dolphins are smart. - Les dauphins sont intelligents."),
                ("Whale", "Baleine", "The whale is huge. - La baleine est énorme."),
                ("Shark", "Requin", "The shark is dangerous. - Le requin est dangereux."),
                ("Octopus", "Poulpe", "The octopus has eight arms. - Le poulpe a huit bras."),
                ("Jellyfish", "Méduse", "The jellyfish stings. - La méduse pique."),
                ("Seahorse", "Hippocampe", "The seahorse is tiny. - L'hippocampe est minuscule."),
            ]},
            {"title": "Insects", "words": [
                ("Butterfly", "Papillon", "The butterfly is beautiful. - Le papillon est beau."),
                ("Bee", "Abeille", "Bees make honey. - Les abeilles font du miel."),
                ("Ant", "Fourmi", "Ants work together. - Les fourmis travaillent ensemble."),
                ("Ladybug", "Coccinelle", "The ladybug is red. - La coccinelle est rouge."),
                ("Spider", "Araignée", "The spider makes a web. - L'araignée fait une toile."),
                ("Dragonfly", "Libellule", "The dragonfly flies fast. - La libellule vole vite."),
            ]},
            {"title": "Trees & Plants", "words": [
                ("Oak", "Chêne", "The oak is old. - Le chêne est vieux."),
                ("Maple", "Érable", "Maple syrup comes from maple. - Le sirop d'érable vient de l'érable."),
                ("Pine", "Pin", "Pine trees stay green. - Les pins restent verts."),
                ("Willow", "Saule", "The willow hangs low. - Le saule pend bas."),
                ("Rose", "Rose", "The rose smells sweet. - La rose sent doux."),
                ("Sunflower", "Tournesol", "The sunflower follows the sun. - Le tournesol suit le soleil."),
            ]},
            {"title": "Flowers", "words": [
                ("Tulip", "Tulipe", "Tulips bloom in spring. - Les tulipes fleurissent au printemps."),
                ("Daisy", "Marguerite", "The daisy is white. - La marguerite est blanche."),
                ("Lily", "Lis", "The lily is elegant. - Le lis est élégant."),
                ("Orchid", "Orchidée", "Orchids are exotic. - Les orchidées sont exotiques."),
                ("Lavender", "Lavande", "Lavender smells nice. - La lavande sent bon."),
                ("Violet", "Violette", "The violet is purple. - La violette est violette."),
            ]},
            {"title": "Nature Elements", "words": [
                ("River", "Rivière", "The river flows. - La rivière coule."),
                ("Mountain", "Montagne", "The mountain is high. - La montagne est haute."),
                ("Valley", "Vallée", "The valley is green. - La vallée est verte."),
                ("Lake", "Lac", "The lake is calm. - Le lac est calme."),
                ("Forest", "Forêt", "The forest is dense. - La forêt est dense."),
                ("Desert", "Désert", "The desert is dry. - Le désert est sec."),
            ]},
            {"title": "Ocean & Sea", "words": [
                ("Ocean", "Océan", "The ocean is vast. - L'océan est vaste."),
                ("Beach", "Plage", "The beach is sandy. - La plage est sablonneuse."),
                ("Wave", "Vague", "The waves are big. - Les vagues sont grandes."),
                ("Coral", "Corail", "Coral reefs are colorful. - Les récifs coralliens sont colorés."),
                ("Tide", "Marée", "High tide is coming. - La marée haute arrive."),
                ("Shell", "Coquillage", "I found a shell. - J'ai trouvé un coquillage."),
            ]},
            {"title": "Weather Phenomena", "words": [
                ("Rainbow", "Arc-en-ciel", "The rainbow is colorful. - L'arc-en-ciel est coloré."),
                ("Lightning", "Éclair", "Lightning struck the tree. - L'éclair a frappé l'arbre."),
                ("Thunder", "Tonnerre", "Thunder is loud. - Le tonnerre est fort."),
                ("Tornado", "Tornade", "The tornado destroyed houses. - La tornade a détruit des maisons."),
                ("Hurricane", "Ouragan", "The hurricane is approaching. - L'ouragan approche."),
                ("Flood", "Inondation", "The flood covered the fields. - L'inondation a couvert les champs."),
            ]},
            {"title": "Reptiles & Amphibians", "words": [
                ("Snake", "Serpent", "The snake slithers. - Le serpent rampe."),
                ("Turtle", "Tortue", "The turtle is slow. - La tortue est lente."),
                ("Frog", "Grenouille", "The frog jumps. - La grenouille saute."),
                ("Lizard", "Lézard", "The lizard basks in the sun. - Le lézard se chauffe au soleil."),
                ("Crocodile", "Crocodile", "The crocodile is dangerous. - Le crocodile est dangereux."),
                ("Chameleon", "Caméléon", "The chameleon changes color. - Le caméléon change de couleur."),
            ]},
            {"title": "Extinct Animals", "words": [
                ("Dinosaur", "Dinosaure", "Dinosaurs lived millions of years ago. - Les dinosaures vivaient il y a des millions d'années."),
                ("Mammoth", "Mammouth", "The mammoth had fur. - Le mammouth avait de la fourrure."),
                ("Dodo", "Dodo", "The dodo is extinct. - Le dodo est éteint."),
                ("Fossil", "Fossile", "We found a fossil. - Nous avons trouvé un fossile."),
                ("Pterodactyl", "Ptérodactyle", "The pterodactyl flew. - Le ptérodactyle volait."),
                ("Sabertooth", "Sabre-toothed", "The sabertooth tiger is extinct. - Le tigre à dents de sabre est éteint."),
            ]},
            {"title": "Animal Sounds", "words": [
                ("Bark", "Aboiement", "The dog barked. - Le chien a aboyé."),
                ("Meow", " Miaulement", "The cat says meow. - Le chat fait miaou."),
                ("Roar", "Rugissement", "The lion roared. - Le lion a rugi."),
                ("Howl", "Hurlement", "The wolf howled. - Le loup a hurlé."),
                ("Chirp", "Gazouillis", "The bird chirped. - L'oiseau a gazouillé."),
                ("Croak", "Coassement", "The frog croaked. - La grenouille a coassé."),
            ]},
            {"title": "Animal Homes", "words": [
                ("Nest", "Nid", "Birds live in nests. - Les oiseaux vivent dans des nids."),
                ("Den", "Tanière", "The bear sleeps in its den. - L'ours dort dans sa tanière."),
                ("Burrow", "Terrier", "The rabbit is in its burrow. - Le lapin est dans son terrier."),
                ("Hive", "Ruche", "Bees live in a hive. - Les abeilles vivent dans une ruche."),
                ("Aquarium", "Aquarium", "Fish live in an aquarium. - Les poissons vivent dans un aquarium."),
                ("Cage", "Cage", "The bird is in a cage. - L'oiseau est dans une cage."),
            ]},
        ]
    },
    # Category 3: Body Parts & Health (Cards 76-90, 15 cards)
    {
        "name": "Body Parts & Health",
        "cards": [
            {"title": "Head Parts", "words": [
                ("Head", "Tête", "The head contains the brain. - La tête contient le cerveau."),
                ("Brain", "Cerveau", "The brain thinks. - Le cerveau pense."),
                ("Eye", "Œil", "I see with my eyes. - Je vois avec mes yeux."),
                ("Ear", "Oreille", "I hear with my ears. - J'entends avec mes oreilles."),
                ("Nose", "Nez", "I smell with my nose. - Je sens avec mon nez."),
                ("Mouth", "Bouche", "I speak with my mouth. - Je parle avec ma bouche."),
            ]},
            {"title": "Face Features", "words": [
                ("Cheek", "Joue", "Her cheeks are red. - Ses joues sont rouges."),
                ("Chin", "Menton", "He has a strong chin. - Il a un menton fort."),
                ("Forehead", "Front", "She has a high forehead. - Elle a le front haut."),
                ("Lip", "Lèvre", "Her lips are red. - Ses lèvres sont rouges."),
                ("Teeth", "Dents", "Brush your teeth. - Brosse tes dents."),
                ("Tongue", "Langue", "The tongue tastes. - La langue goûte."),
            ]},
            {"title": "Arm & Hand", "words": [
                ("Arm", "Bras", "I raise my arm. - Je lève mon bras."),
                ("Elbow", "Coude", "My elbow hurts. - Mon coude me fait mal."),
                ("Wrist", "Poignet", "She wears a bracelet on her wrist. - Elle porte un bracelet à son poignet."),
                ("Hand", "Main", "I wave my hand. - Je fais un signe de la main."),
                ("Finger", "Doigt", "I point with my finger. - Je pointe du doigt."),
                ("Thumb", "Pouce", "The thumb is important. - Le pouce est important."),
            ]},
            {"title": "Leg & Foot", "words": [
                ("Leg", "Jambe", "I broke my leg. - Je me suis cassé la jambe."),
                ("Knee", "Genou", "The knee bends. - Le genou se plie."),
                ("Calf", "Mollet", "The calf muscle is strong. - Le muscle du mollet est fort."),
                ("Ankle", "Cheville", "My ankle is swollen. - Ma cheville est enflée."),
                ("Foot", "Pied", "I step on my foot. - Je marche sur mon pied."),
                ("Toe", "Orteil", "I stubbed my toe. - Je me suis cogné l'orteil."),
            ]},
            {"title": "Torso", "words": [
                ("Chest", "Poitrine", "His chest is broad. - Sa poitrine est large."),
                ("Heart", "Cœur", "The heart beats. - Le cœur bat."),
                ("Lung", "Poumon", "The lungs breathe. - Les poumons respirent."),
                ("Stomach", "Estomac", "My stomach aches. - Mon estomac me fait mal."),
                ("Liver", "Foie", "The liver filters blood. - Le foie filtre le sang."),
                ("Kidney", "Rein", "The kidneys filter waste. - Les reins filtrent les déchets."),
            ]},
            {"title": "Bones & Muscles", "words": [
                ("Bone", "Os", "The bone is strong. - L'os est fort."),
                ("Muscle", "Muscle", "Exercise builds muscle. - L'exercice construit du muscle."),
                ("Skeleton", "Squelette", "The skeleton supports the body. - Le squelette supporte le corps."),
                ("Spine", "Colonne vertébrale", "The spine is flexible. - La colonne vertébrale est flexible."),
                ("Joint", "Articulation", "The joint allows movement. - L'articulation permet le mouvement."),
                ("Tendon", "Tendon", "The tendon connects muscle to bone. - Le tendon relie le muscle à l'os."),
            ]},
            {"title": "Skin & Hair", "words": [
                ("Skin", "Peau", "Skin protects the body. - La peau protège le corps."),
                ("Hair", "Cheveux", "She has long hair. - Elle a de longs cheveux."),
                ("Beard", "Barbe", "He has a beard. - Il a une barbe."),
                ("Mustache", "Moustache", "The mustache is curly. - La moustache est frisée."),
                ("Nail", "Ongle", "Cut your nails. - Coupe tes ongles."),
                ("Freckle", "Tache de rousseur", "She has freckles. - Elle a des taches de rousseur."),
            ]},
            {"title": "Health Problems", "words": [
                ("Headache", "Mal de tête", "I have a headache. - J'ai mal à la tête."),
                ("Cold", "Rhume", "I caught a cold. - J'ai attrapé un rhume."),
                ("Fever", "Fièvre", "The fever is high. - La fièvre est haute."),
                ("Cough", "Toux", "The cough won't stop. - La toux ne s'arrête pas."),
                ("Stomachache", "Mal de ventre", "I have a stomachache. - J'ai mal au ventre."),
                ("Backache", "Mal de dos", "My back hurts. - J'ai mal au dos."),
            ]},
            {"title": "Medical Terms", "words": [
                ("Doctor", "Médecin", "The doctor examined me. - Le médecin m'a examiné."),
                ("Nurse", "Infirmier", "The nurse gave me medicine. - L'infirmier m'a donné des médicaments."),
                ("Hospital", "Hôpital", "She works at the hospital. - Elle travaille à l'hôpital."),
                ("Medicine", "Médicament", "Take your medicine. - Prends ton médicament."),
                ("Surgery", "Chirurgie", "The surgery was successful. - La chirurgie a réussi."),
                ("Appointment", "Rendez-vous", "I have a doctor's appointment. - J'ai un rendez-vous chez le médecin."),
            ]},
            {"title": "Body Actions", "words": [
                ("Breathe", "Respirer", "Breathe deeply. - Respire profondément."),
                ("Swallow", "Avaler", "Swallow the pill. - Avale le comprimé."),
                ("Sneeze", "Éternuer", "I need to sneeze. - Je dois éternuer."),
                ("Yawn", "Bâiller", "I can't stop yawning. - Je n'arrive pas à arrêter de bâiller."),
                ("Blink", "Cligner", "Blink your eyes. - Cligne des yeux."),
                ("Shiver", "Frissonner", "I'm shivering. - Je frissonne."),
            ]},
            {"title": "Senses", "words": [
                ("Sight", "Vue", "My sight is good. - Ma vue est bonne."),
                ("Hearing", "Audition", "My hearing is fine. - Mon audition est bonne."),
                ("Smell", "Odorat", "Dogs have good smell. - Les chiens ont un bon odorat."),
                ("Taste", "Goût", "The taste is sweet. - Le goût est sucré."),
                ("Touch", "Toucher", "The touch is soft. - Le toucher est doux."),
                ("Sixth sense", "Sixième sens", "It's my sixth sense. - C'est mon sixième sens."),
            ]},
            {"title": "Physical States", "words": [
                ("Tired", "Fatigué", "I'm tired. - Je suis fatigué."),
                ("Hungry", "Affamé", "I'm hungry. - J'ai faim."),
                ("Thirsty", "Assoiffé", "I'm thirsty. - J'ai soif."),
                ("Sleepy", "Endormi", "I'm sleepy. - Je suis endormi."),
                ("Weak", "Faible", "I feel weak. - Je me sens faible."),
                ("Dizzy", "Étourdi", "The room is spinning. - J'ai la tête qui tourne."),
            ]},
            {"title": "Healthy Habits", "words": [
                ("Exercise", "Exercice", "Exercise daily. - Fais de l'exercice quotidiennement."),
                ("Sleep", "Dormir", "I sleep eight hours. - Je dors huit heures."),
                ("Hydrate", "S'hydrater", "Drink water to hydrate. - Bois de l'eau pour t'hydrater."),
                ("Balanced diet", "Régime équilibré", "Eat a balanced diet. - Mange équilibré."),
                ("Rest", "Se reposer", "Rest is important. - Le repos est important."),
                ("Vaccination", "Vaccination", "Get your vaccination. - Fais ta vaccination."),
            ]},
            {"title": "Emergency", "words": [
                ("Emergency", "Urgence", "Call emergency! - Appelez les urgences!"),
                ("Ambulance", "Ambulance", "The ambulance is coming. - L'ambulance arrive."),
                ("First aid", "Premiers secours", "I know first aid. - Je connais les premiers secours."),
                ("Bleeding", "Saignement", "Stop the bleeding. - Arrête le saignement."),
                ("Bandage", "Pansement", "Put a bandage on it. - Mets un pansement dessus."),
                ("Unconscious", "Inconscient", "He is unconscious. - Il est inconscient."),
            ]},
        ]
    },
    # Category 4: Food & Drinks (Cards 91-105, 15 cards)
    {
        "name": "Food & Drinks",
        "cards": [
            {"title": "Fruits", "words": [
                ("Apple", "Pomme", "An apple a day. - Une pomme par jour."),
                ("Banana", "Banane", "The banana is ripe. - La banane est mûre."),
                ("Orange", "Orange", "I juice oranges. - Je fais du jus d'orange."),
                ("Strawberry", "Fraise", "Strawberries are red. - Les fraises sont rouges."),
                ("Grape", "Raisin", "Grapes grow in clusters. - Les raisins poussent en grappes."),
                ("Watermelon", "Pastèque", "Watermelon is refreshing. - La pastèque est rafraîchissante."),
            ]},
            {"title": "Vegetables", "words": [
                ("Carrot", "Carotte", "Carrots are orange. - Les carottes sont oranges."),
                ("Tomato", "Tomate", "The tomato is red. - La tomate est rouge."),
                ("Potato", "Pomme de terre", "Boiled potato please. - Pommes de terre natures s'il vous plaît."),
                ("Lettuce", "Laitue", "Lettuce is in salads. - La laitue est dans les salades."),
                ("Onion", "Oignon", "The onion makes me cry. - L'oignon me fait pleurer."),
                ("Cucumber", "Concombre", "Cucumber is cool. - Le concombre est frais."),
            ]},
            {"title": "Meat & Poultry", "words": [
                ("Beef", "Bœuf", "Beef steak is delicious. - Le steak de bœuf est délicieux."),
                ("Pork", "Porc", "Pork is meat from pigs. - Le porc est la viande des cochons."),
                ("Chicken", "Poulet", "Roasted chicken for dinner. - Poulet rôti pour le dîner."),
                ("Turkey", "Dinde", "Turkey is for Thanksgiving. - La dinde est pour Thanksgiving."),
                ("Lamb", "Agneau", "Lamb chops are tasty. - Les côtelettes d'agneau sont savoureuses."),
                ("Veal", "Veau", "Veal is young cow. - Le veau est un jeune bovin."),
            ]},
            {"title": "Fish & Seafood", "words": [
                ("Salmon", "Saumon", "Grilled salmon. - Saumon grillé."),
                ("Tuna", "Thon", "Tuna salad sandwich. - Sandwich à la salade de thon."),
                ("Cod", "Cabillaud", "Fish and chips with cod. - Fish and chips au cabillaud."),
                ("Shrimp", "Crevette", "Shrimp are pink. - Les crevettes sont roses."),
                ("Lobster", "Homard", "Lobster is expensive. - Le homard est cher."),
                ("Crab", "Crabe", "Crab legs for appetizer. - Des pattes de crabe en entrée."),
            ]},
            {"title": "Dairy", "words": [
                ("Milk", "Lait", "A glass of milk. - Un verre de lait."),
                ("Cheese", "Fromage", "French cheese is famous. - Le fromage français est célèbre."),
                ("Butter", "Beurre", "Put butter on bread. - Mets du beurre sur le pain."),
                ("Yogurt", "Yaourt", "Yogurt with fruit. - Yaourt aux fruits."),
                ("Cream", "Crème", "Whipped cream on cake. - Crème chantilly sur le gâteau."),
                ("Ice cream", "Glace", "Two scoops of ice cream. - Deux boules de glace."),
            ]},
            {"title": "Breads & Grains", "words": [
                ("Bread", "Pain", "Fresh bread from the bakery. - Pain frais de la boulangerie."),
                ("Croissant", "Croissant", "A buttery croissant. - Un croissant beurré."),
                ("Rice", "Riz", "Steamed rice with meals. - Riz vapeur avec les repas."),
                ("Pasta", "Pâtes", "Pasta for dinner tonight. - Des pâtes pour le dîner ce soir."),
                ("Noodles", "Nouilles", "Asian noodles are good. - Les nouilles asiatiques sont bonnes."),
                ("Cereal", "Céréales", "Breakfast cereal with milk. - Céréales du petit-déjeuner avec du lait."),
            ]},
            {"title": "Drinks", "words": [
                ("Water", "Eau", "A bottle of water. - Une bouteille d'eau."),
                ("Coffee", "Café", "Morning coffee is essential. - Le café du matin est essentiel."),
                ("Tea", "Thé", "Herbal tea before bed. - Thé aux herbes avant de dormir."),
                ("Juice", "Jus", "Orange juice for breakfast. - Jus d'orange au petit-déjeuner."),
                ("Soda", "Soda", "Too much soda is bad. - Trop de soda c'est mauvais."),
                ("Milkshake", "Milkshake", "Chocolate milkshake please. - Milkshake au chocolat s'il vous plaît."),
            ]},
            {"title": "Hot Drinks", "words": [
                ("Hot chocolate", "Chocolat chaud", "Hot chocolate on cold days. - Chocolat chaud les jours froids."),
                ("Latte", "Latté", "A vanilla latte. - Un latté à la vanille."),
                ("Cappuccino", "Cappuccino", "Foamy cappuccino. - Cappuccino mousseux."),
                ("Espresso", "Espresso", "A strong espresso. - Un espresso fort."),
                ("Macchiato", "Macchiato", "Caramel macchiato. - Macchiato au caramel."),
                ("Mocha", "Moka", "Chocolate mocha coffee. - Café moka au chocolat."),
            ]},
            {"title": "Sweets & Desserts", "words": [
                ("Chocolate", "Chocolat", "Dark chocolate is healthy. - Le chocolat noir est sain."),
                ("Cake", "Gâteau", "Birthday cake time! - C'est l'heure du gâteau d'anniversaire!"),
                ("Cookie", "Biscuit", "Chocolate chip cookies. - Biscuits aux pépites de chocolat."),
                ("Candy", "Bonbon", "Kids love candy. - Les enfants adorent les bonbons."),
                ("Pie", "Tarte", "Apple pie is American. - La tarte aux pommes est américaine."),
                ("Pudding", "Budino", "Vanilla pudding dessert. - Dessert budino à la vanille."),
            ]},
            {"title": "Spices & Seasonings", "words": [
                ("Salt", "Sel", "Pass the salt. - Passe le sel."),
                ("Pepper", "Poivre", "Black pepper please. - Poivre noir s'il vous plaît."),
                ("Sugar", "Sucre", "Two sugars in my coffee. - Deux sucres dans mon café."),
                ("Cinnamon", "Cannelle", "Cinnamon on apples. - De la cannelle sur les pommes."),
                ("Oregano", "Origan", "Oregano on pizza. - De l'origan sur la pizza."),
                ("Basil", "Basilic", "Fresh basil pesto. - Pesto au basilic frais."),
            ]},
            {"title": "Breakfast", "words": [
                ("Eggs", "Œufs", "Scrambled eggs for breakfast. - Œufs brouillés au petit-déjeuner."),
                ("Bacon", "Bacon", "Crispy bacon strips. - Tranches de bacon croustillantes."),
                ("Pancakes", "Crêpes", "Stack of pancakes. - Une pile de crêpes."),
                ("Waffles", "Gaufres", "Belgian waffles. - Gaufres belges."),
                ("Oatmeal", "Porridge", "Warm oatmeal in winter. - Porridge chaud en hiver."),
                ("Toast", "Toast", "Buttered toast. - Toast beurré."),
            ]},
            {"title": "Lunch & Dinner", "words": [
                ("Sandwich", "Sandwich", "Ham sandwich for lunch. - Sandwich au jambon pour le déjeuner."),
                ("Salad", "Salade", "Caesar salad please. - Salade César s'il vous plaît."),
                ("Soup", "Soupe", "Hot vegetable soup. - Soupe chaude aux légumes."),
                ("Steak", "Steak", "Medium rare steak. - Steak à point."),
                ("Roast", "Rôti", "Sunday roast dinner. - Rôti du dimanche."),
                ("Grill", "Grillade", "Summer grill party. - Fête au grill en été."),
            ]},
            {"title": "Snacks", "words": [
                ("Chips", "Chips", "Potato chips are salty. - Les chips de pommes de terre sont salées."),
                ("Popcorn", "Popcorn", "Movie theater popcorn. - Popcorn du cinéma."),
                ("Nuts", "Noix", "Mixed nuts for snacking. - Mélange de noix pour grignoter."),
                ("Pretzel", "Prétzel", "Salty pretzel sticks. - Bâtons de prétzel salés."),
                ("Granola bar", "Barre de céréales", "Energy granola bar. - Barre de céréales énergétiques."),
                ("Fruit snack", "Bonbon de fruits", "Gummy fruit snacks. - Bonbons gélifiés aux fruits."),
            ]},
            {"title": "Condiments", "words": [
                ("Ketchup", "Ketchup", "Ketchup on fries. - Du ketchup avec les frites."),
                ("Mustard", "Moutarde", "Yellow mustard on hot dog. - Moutarde jaune sur hot dog."),
                ("Mayonnaise", "Mayonnaise", "Mayo on my sandwich. - Mayo sur mon sandwich."),
                ("Soy sauce", "Sauce soja", "Soy sauce for sushi. - Sauce soja pour sushi."),
                ("Hot sauce", "Sauce piquante", "Extra hot sauce please. - Sauce piquante supplémentaire."),
                ("Vinegar", "Vinaigre", "Oil and vinegar dressing. - Vinaigrette huile et vinaigre."),
            ]},
        ]
    },
    # Category 5: Electronics & Tech (Cards 106-120, 15 cards)
    {
        "name": "Electronics & Tech",
        "cards": [
            {"title": "Devices", "words": [
                ("Smartphone", "Smartphone", "Check your smartphone. - Vérifie ton smartphone."),
                ("Tablet", "Tablette", "The tablet is touch screen. - La tablette est tactile."),
                ("Laptop", "Ordinateur portable", "My laptop is fast. - Mon ordinateur portable est rapide."),
                ("Computer", "Ordinateur", "Desktop computer setup. - Configuration ordinateur de bureau."),
                ("Smartwatch", "Montre connectée", "My smartwatch tracks steps. - Ma montre connectée compte les pas."),
                ("E-reader", "Liseuse", "I read on my e-reader. - Je lis sur ma liseuse."),
            ]},
            {"title": "Computer Parts", "words": [
                ("Screen", "Écran", "The screen is bright. - L'écran est lumineux."),
                ("Keyboard", "Clavier", "Wireless keyboard. - Clavier sans fil."),
                ("Mouse", "Souris", "Click the mouse. - Clique la souris."),
                ("Speaker", "Haut-parleur", "External speakers. - Haut-parleurs externes."),
                ("Webcam", "Webcam", "Turn on the webcam. - Active la webcam."),
                ("Microphone", "Microphone", "Studio microphone. - Microphone de studio."),
            ]},
            {"title": "Internet", "words": [
                ("WiFi", "WiFi", "Password for WiFi? - Le mot de passe WiFi?"),
                ("Browser", "Navigateur", "Open a new browser tab. - Ouvre un nouvel onglet."),
                ("Website", "Site web", "Visit our website. - Visitez notre site web."),
                ("Download", "Télécharger", "Download the file. - Télécharge le fichier."),
                ("Upload", "Téléverser", "Upload your photo. - Téléverse ta photo."),
                ("Streaming", "Streaming", "Movie streaming service. - Service de streaming de films."),
            ]},
            {"title": "Social Media", "words": [
                ("Post", "Publication", "Make a post. - Fais une publication."),
                ("Follow", "Suivre", "Follow me on Instagram. - Suis-moi sur Instagram."),
                ("Like", "Aimer", "Like my photo. - Like ma photo."),
                ("Share", "Partager", "Share this video. - Partage cette vidéo."),
                ("Comment", "Commenter", "Leave a comment. - Laisse un commentaire."),
                ("Hashtag", "Hashtag", "Add a hashtag. - Ajoute un hashtag."),
            ]},
            {"title": "Apps & Software", "words": [
                ("App", "Application", "Download the app. - Télécharge l'application."),
                ("Update", "Mise à jour", "Update your apps. - Mets à jour tes applications."),
                ("Install", "Installer", "Install the software. - Installe le logiciel."),
                ("Uninstall", "Désinstaller", "Uninstall unused apps. - Désinstalle les applications inutilisées."),
                ("Settings", "Paramètres", "Check app settings. - Vérifie les paramètres."),
                ("Notification", "Notification", "Turn off notifications. - Désactive les notifications."),
            ]},
            {"title": "Gaming", "words": [
                ("Video game", "Jeu vidéo", "New video game release. - Nouvelle sortie de jeu vidéo."),
                ("Controller", "Manette", "Gaming controller. - Manette de jeu."),
                ("Headset", "Casque", "Gaming headset with microphone. - Casque de jeu avec micro."),
                ("Console", "Console", "Next-gen console. - Console de nouvelle génération."),
                ("Level", "Niveau", "Beat this level. - Termine ce niveau."),
                ("Score", "Score", "High score leaderboard. - Classement des scores élevés."),
            ]},
            {"title": "Photography", "words": [
                ("Camera", "Appareil photo", "DSLR camera. - Appareil photo reflex."),
                ("Photo", "Photo", "Take a photo. - Prends une photo."),
                ("Selfie", "Selfie", "Take a selfie. - Prends un selfie."),
                ("Flash", "Flash", "Turn on the flash. - Active le flash."),
                ("Zoom", "Zoom", "Zoom in to focus. - Zoom avant pour faire la mise au point."),
                ("Filter", "Filtre", "Apply a filter. - Applique un filtre."),
            ]},
            {"title": "Music Tech", "words": [
                ("Headphones", "Écouteurs", "Wireless headphones. - Écouteurs sans fil."),
                ("Earbuds", "Ecouteurs", "Bluetooth earbuds. - Écouteurs Bluetooth."),
                ("Speaker", "Haut-parleur", "Bluetooth speaker. - Haut-parleur Bluetooth."),
                ("MP3 player", "Lecteur MP3", "Old school MP3 player. - Vieux lecteur MP3."),
                ("DJ equipment", "Équipement DJ", "Professional DJ equipment. - Équipement DJ professionnel."),
                ("Amplifier", "Amplificateur", "Guitar amplifier. - Amplificateur de guitare."),
            ]},
            {"title": "TV & Video", "words": [
                ("Television", "Télévision", "Watch television. - Regarder la télévision."),
                ("Remote", "Télécommande", "Where's the remote? - Où est la télécommande?"),
                ("Channel", "Chaîne", "Change the channel. - Change de chaîne."),
                ("Volume", "Volume", "Turn up the volume. - Monte le son."),
                ("HDMI", "HDMI", "HDMI cable connection. - Connexion cable HDMI."),
                ("Projector", "Projecteur", "Movie projector. - Projecteur de cinéma."),
            ]},
            {"title": "Data & Storage", "words": [
                ("Memory", "Mémoire", "Not enough memory. - Pas assez de mémoire."),
                ("Storage", "Stockage", "Cloud storage options. - Options de stockage cloud."),
                ("USB", "Clé USB", "USB flash drive. - Clé USB."),
                ("Hard drive", "Disque dur", "External hard drive. - Disque dur externe."),
                ("Backup", "Sauvegarde", "Backup your files. - Sauvegarde tes fichiers."),
                ("Cloud", "Cloud", "Store in the cloud. - Stocke dans le cloud."),
            ]},
            {"title": "Tech Problems", "words": [
                ("Bug", "Bug", "Software bug found. - Bug logiciel trouvé."),
                ("Crash", "Plantage", "The app crashed. - L'application a planté."),
                ("Virus", "Virus", "Computer virus alert. - Alerte virus informatique."),
                ("Hacker", "Pirate", "Hacker attack prevention. - Prévention des attaques de pirates."),
                ("Password", "Mot de passe", "Change your password. - Change ton mot de passe."),
                ("Battery", "Batterie", "Low battery warning. - Avertissement batterie faible."),
            ]},
            {"title": "Programming", "words": [
                ("Code", "Code", "Write code. - Écris du code."),
                ("Bug", "Bug", "Debug the code. - Débogue le code."),
                ("Function", "Fonction", "This function works. - Cette fonction marche."),
                ("Variable", "Variable", "Define a variable. - Définis une variable."),
                ("Loop", "Boucle", "For loop syntax. - Syntaxe de boucle for."),
                ("Algorithm", "Algorithme", "Algorithm optimization. - Optimisation d'algorithme."),
            ]},
            {"title": "AI & Future Tech", "words": [
                ("Robot", "Robot", "Industrial robot arm. - Bras de robot industriel."),
                ("Drone", "Drone", "Flying drone camera. - Caméra de drone volant."),
                ("3D printing", "Impression 3D", "3D printed objects. - Objets imprimés en 3D."),
                ("Virtual reality", "Réalité virtuelle", "VR headset experience. - Expérience avec casque VR."),
                ("Augmented reality", "Réalité augmentée", "AR gaming apps. - Applications de jeu en AR."),
                ("Blockchain", "Blockchain", "Blockchain technology. - Technologie blockchain."),
            ]},
            {"title": "Communication", "words": [
                ("Email", "Email", "Send an email. - Envoie un email."),
                ("Message", "Message", "Text message received. - Message texte reçu."),
                ("Video call", "Appel vidéo", "Let's do a video call. - Faisons un appel vidéo."),
                ("Voicemail", "Messagerie", "Check your voicemail. - Vérifie ta messagerie."),
                ("Chat", "Discussion", "Online chat support. - Support par discussion en ligne."),
                ("Conference", "Conférence", "Work conference call. - Appel conférence de travail."),
            ]},
        ]
    },
    # Category 6: Arts & Media (Cards 121-135, 15 cards)
    {
        "name": "Arts & Media",
        "cards": [
            {"title": "Music", "words": [
                ("Song", "Chanson", "My favorite song. - Ma chanson préférée."),
                ("Singer", "Chanteur", "The singer is talented. - Le chanteuse est talentueuse."),
                ("Band", "Groupe", "Rock band concert. - Concert de groupe de rock."),
                ("Concert", "Concert", "Music concert tonight. - Concert de musique ce soir."),
                ("Melody", "Mélodie", "Sweet melody. - Douce mélodie."),
                ("Rhythm", "Rythme", "Dance to the rhythm. - Danse sur le rythme."),
            ]},
            {"title": "Musical Instruments", "words": [
                ("Guitar", "Guitare", "Acoustic guitar strings. - Cordes de guitare acoustique."),
                ("Piano", "Piano", "Play the piano. - Joue du piano."),
                ("Drums", "Batterie", "Drum set kit. - Kit de batterie."),
                ("Violin", "Violon", "Classical violin music. - Musique classique de violon."),
                ("Trumpet", "Trompette", "Brass trumpet sound. - Son de trompe."),
                ("Flute", "Flûte", "Bamboo flute. - Flûte de bambou."),
            ]},
            {"title": "Painting & Art", "words": [
                ("Painting", "Tableau", "Famous painting in museum. - Tableau célèbre au musée."),
                ("Artist", "Artiste", "The artist is creative. - L'artiste est créatif."),
                ("Canvas", "Toile", "Paint on canvas. - Peins sur toile."),
                ("Brush", "Pinceau", "Paintbrush strokes. - Coups de pinceau."),
                ("Palette", "Palette", "Artist's color palette. - Palette de couleurs de l'artiste."),
                ("Portrait", "Portrait", "Oil portrait painting. - Peinture de portrait à l'huile."),
            ]},
            {"title": "Movies & Film", "words": [
                ("Movie", "Film", "New movie release. - Nouvelle sortie de film."),
                ("Actor", "Acteur", "Famous movie actor. - Acteur de film célèbre."),
                ("Actress", "Actrice", "Oscar winning actress. - Actrice primée aux Oscars."),
                ("Director", "Réalisateur", "Film director. - Le réalisateur de film."),
                ("Scene", "Scène", "Action scene. - Scène d'action."),
                ("Trailer", "Bande-annonce", "Movie trailer online. - Bande-annonce de film en ligne."),
            ]},
            {"title": "Theater", "words": [
                ("Theater", "Théâtre", "Broadway theater show. - Spectacle de théâtre Broadway."),
                ("Stage", "Scène", "On stage performing. - En train de performer sur scène."),
                ("Audience", "Public", "The audience applauded. - Le public a applaudi."),
                ("Curtain", "Rideau", "The curtain rose. - Le rideau s'est levé."),
                ("Drama", "Drame", "Theater drama performance. - Performance de drame théâtral."),
                ("Comedy", "Comédie", "Funny comedy show. - Spectacle de comédie marrant."),
            ]},
            {"title": "Literature", "words": [
                ("Book", "Livre", "Read a book. - Lis un livre."),
                ("Author", "Auteur", "Famous author visit. - Visite d'un auteur célèbre."),
                ("Novel", "Roman", "Bestselling novel. - Roman à succès."),
                ("Poem", "Poème", "Write a poem. - Écris un poème."),
                ("Chapter", "Chapitre", "Read the next chapter. - Lis le chapitre suivant."),
                ("Character", "Personnage", "Main character development. - Développement du personnage principal."),
            ]},
            {"title": "Photography", "words": [
                ("Portrait", "Portrait", "Professional portrait photo. - Photo de portrait professionnelle."),
                ("Landscape", "Paysage", "Beautiful landscape shot. - Belle photo de paysage."),
                ("Aperture", "Ouverture", "Camera aperture setting. - Réglage d'ouverture de l'appareil."),
                ("Exposure", "Exposition", "Photo exposure time. - Temps d'exposition photo."),
                ("Snapshot", "Instantané", "Quick snapshot moment. - Moment d'instantané rapide."),
                ("Framing", "Cadrage", "Creative photo framing. - Cadrage photo créatif."),
            ]},
            {"title": "Dance", "words": [
                ("Dance", "Danse", "Dance performance. - Spectacle de danse."),
                ("Ballet", "Ballet", "Classical ballet show. - Spectacle de ballet classique."),
                ("Hip hop", "Hip hop", "Hip hop dance style. - Style de danse hip hop."),
                ("Salsa", "Salsa", "Latin salsa dancing. - Danse salsa latine."),
                ("Waltz", "Valse", "Elegant waltz music. - Musique de valse élégante."),
                ("Choreography", "Chorégraphie", "Dance choreography. - Chorégraphe de danse."),
            ]},
            {"title": "Fashion", "words": [
                ("Designer", "Créateur", "Fashion designer brand. - Marque de créateur de mode."),
                ("Runway", "Défilé", "Fashion runway show. - Défilé de mode sur runway."),
                ("Trend", "Tendance", "Latest fashion trend. - Dernière tendance mode."),
                ("Collection", "Collection", "New clothing collection. - Nouvelle collection de vêtements."),
                ("Style", "Style", "Personal style expression. - Expression du style personnel."),
                ("Vintage", "Vintage", "Vintage clothing store. - Magasin de vêtements vintage."),
            ]},
            {"title": "News & Media", "words": [
                ("Newspaper", "Journal", "Daily newspaper delivery. - Livraison du journal quotidien."),
                ("Headline", "Titre", "Breaking news headline. - Titre d'actualité urgente."),
                ("Journalist", "Journaliste", "Investigative journalist. - Journaliste d'investigation."),
                ("Reporter", "Reporter", "News reporter live. - Reporter en direct."),
                ("Broadcast", "Diffusion", "Live broadcast coverage. - Couverture en direct."),
                ("Podcast", "Balado", "True crime podcast. - Balado true crime."),
            ]},
            {"title": "Museums", "words": [
                ("Museum", "Musée", "Visit the art museum. - Visite du musée d'art."),
                ("Exhibit", "Exposition", "Special exhibit opening. - Ouverture d'exposition spéciale."),
                ("Artifact", "Artefact", "Ancient artifact display. - Affichage d'artefact ancien."),
                ("Sculpture", "Sculpture", "Marble sculpture statue. - Statue de sculpture en marbre."),
                ("Gallery", "Galerie", "Art gallery opening. - Ouverture de galerie d'art."),
                ("Curator", "Commissaire", "Museum curator tour. - Visite avec le commissaire."),
            ]},
            {"title": "Graphic Design", "words": [
                ("Design", "Design", "Graphic design work. - Travail de design graphique."),
                ("Logo", "Logo", "Company logo design. - Design de logo d'entreprise."),
                ("Font", "Police", "Choose a different font. - Choisis une autre police."),
                ("Layout", "Mise en page", "Magazine layout design. - Design de mise en page magazine."),
                ("Banner", "Bannière", "Web banner advertisement. - Publicité en bannière web."),
                ("Poster", "Affiche", "Concert poster design. - Design d'affiche de concert."),
            ]},
            {"title": "Animation", "words": [
                ("Animation", "Animation", "Cartoon animation show. - Émission d'animation de dessin animé."),
                ("Cartoon", "Dessin animé", "Kids cartoon character. - Personnage de dessin animé."),
                ("Anime", "Anime", "Japanese anime series. - Série d'anime japonaise."),
                ("Comic", "Bande dessinée", "Superhero comic book. - Livre de bande dessinée superhero."),
                ("Storyboard", "Storyboard", "Film storyboard planning. - Planification storyboard de film."),
                ("Manga", "Manga", "Popular manga series. - Série de manga populaire."),
            ]},
            {"title": "Radio & TV", "words": [
                ("Radio", "Radio", "Listen to the radio. - Écoute la radio."),
                ("Station", "Station", "Radio station frequency. - Fréquence de station radio."),
                ("Host", "Animateur", "Radio show host. - Animateur d'émissions radio."),
                ("Broadcast", "Diffusion", "Live TV broadcast. - Diffusion TV en direct."),
                ("Series", "Série", "TV series marathon. - Marathon de séries TV."),
                ("Episode", "Épisode", "Next episode preview. - Aperçu de l'épisode suivant."),
            ]},
        ]
    },
    # Category 7: Verbs (Cards 136-160, 25 cards)
    {
        "name": "Verbs",
        "cards": [
            {"title": "Action Verbs 1", "words": [
                ("Run", "Courir", "Run to the finish. - Cours jusqu'à la ligne d'arrivée."),
                ("Jump", "Sauter", "Jump over the fence. - Saute par-dessus la barrière."),
                ("Walk", "Marcher", "Walk to school. - Marche jusqu'à l'école."),
                ("Swim", "Nager", "Swim in the pool. - Nage dans la piscine."),
                ("Fly", "Voler", "Birds fly south. - Les oiseaux volent vers le sud."),
                ("Drive", "Conduire", "Drive the car. - Conduis la voiture."),
            ]},
            {"title": "Action Verbs 2", "words": [
                ("Eat", "Manger", "Eat your vegetables. - Mange tes légumes."),
                ("Drink", "Boire", "Drink water please. - Bois de l'eau s'il te plaît."),
                ("Sleep", "Dormir", "Sleep eight hours. - Dors huit heures."),
                ("Read", "Lire", "Read a book tonight. - Lis un livre ce soir."),
                ("Write", "Écrire", "Write in your journal. - Écris dans ton journal."),
                ("Speak", "Parler", "Speak clearly. - Parle clairement."),
            ]},
            {"title": "Communication", "words": [
                ("Talk", "Parler", "Let's talk about it. - Parlons-en."),
                ("Say", "Dire", "Say what you think. - Dis ce que tu penses."),
                ("Ask", "Demander", "Ask a question. - Pose une question."),
                ("Answer", "Répondre", "Answer the phone. - Réponds au téléphone."),
                ("Tell", "Dire", "Tell me a story. - Dis-moi une histoire."),
                ("Explain", "Expliquer", "Explain the problem. - Explique le problème."),
            ]},
            {"title": "Movement", "words": [
                ("Go", "Aller", "Go home now. - Va à la maison maintenant."),
                ("Come", "Venir", "Come here please. - Viens ici s'il te plaît."),
                ("Leave", "Partir", "Leave early tomorrow. - Pars tôt demain."),
                ("Arrive", "Arriver", "Arrive on time. - Arrive à l'heure."),
                ("Move", "Bouger", "Don't move! - Ne bouge pas!"),
                ("Travel", "Voyager", "Travel around Europe. - Voyage à travers l'Europe."),
            ]},
            {"title": "Thinking", "words": [
                ("Think", "Penser", "Think before you speak. - Réfléchis avant de parler."),
                ("Know", "Savoir", "I know the answer. - Je sais la réponse."),
                ("Understand", "Comprendre", "I understand now. - Je comprends maintenant."),
                ("Remember", "Se souvenir", "Remember this moment. - Souviens-toi de ce moment."),
                ("Forget", "Oublier", "Don't forget me. - Ne m'oublie pas."),
                ("Believe", "Croire", "I believe in you. - Je crois en toi."),
            ]},
            {"title": "Emotions", "words": [
                ("Love", "Aimer", "Love your family. - Aime ta famille."),
                ("Hate", "Détester", "I hate waiting. - Je déteste attendre."),
                ("Like", "Aimer", "I like pizza. - J'aime la pizza."),
                ("Want", "Vouloir", "I want this. - Je veux ça."),
                ("Need", "Avoir besoin", "I need help. - J'ai besoin d'aide."),
                ("Feel", "Se sentir", "Feel happy today. - Sens-toi heureux aujourd'hui."),
            ]},
            {"title": "Creation", "words": [
                ("Make", "Faire", "Make breakfast. - Fais le petit-déjeuner."),
                ("Create", "Créer", "Create art. - Crée de l'art."),
                ("Build", "Construire", "Build a house. - Construis une maison."),
                ("Draw", "Dessiner", "Draw a picture. - Dessine une image."),
                ("Paint", "Peindre", "Paint the wall. - Peins le mur."),
                ("Cook", "Cuisiner", "Cook dinner tonight. - Cuisine le dîner ce soir."),
            ]},
            {"title": "Work & Jobs", "words": [
                ("Work", "Travailler", "Work hard today. - Travaille dur aujourd'hui."),
                ("Study", "Étudier", "Study for exams. - Étudie pour les examens."),
                ("Learn", "Apprendre", "Learn French. - Apprends le français."),
                ("Teach", "Enseigner", "Teach the students. - Enseigne aux étudiants."),
                ("Help", "Aider", "Help your neighbor. - Aide ton voisin."),
                ("Serve", "Servir", "Serve customers. - Sers les clients."),
            ]},
            {"title": "Buying & Selling", "words": [
                ("Buy", "Acheter", "Buy groceries. - Achète des provisions."),
                ("Sell", "Vendre", "Sell your old stuff. - Vends tes vieilles choses."),
                ("Pay", "Payer", "Pay the bill. - Paie l'addition."),
                ("Cost", "Coûter", "How much does it cost? - Combien ça coûte?"),
                ("Spend", "Dépenser", "Spend wisely. - Dépense judicieusement."),
                ("Save", "Épargner", "Save money. - Épargne de l'argent."),
            ]},
            {"title": "Time Verbs", "words": [
                ("Start", "Commencer", "Start now. - Commence maintenant."),
                ("Stop", "Arrêter", "Stop right there. - Arrête-toi là."),
                ("Continue", "Continuer", "Continue walking. - Continue à marcher."),
                ("Finish", "Finir", "Finish your work. - Finis ton travail."),
                ("Begin", "Commencer", "Begin the journey. - Commence le voyage."),
                ("End", "Terminer", "End on a high note. - Termine sur une note positive."),
            ]},
            {"title": "Giving & Taking", "words": [
                ("Give", "Donner", "Give me a gift. - Donne-moi un cadeau."),
                ("Take", "Prendre", "Take your time. - Prends ton temps."),
                ("Share", "Partager", "Share with others. - Partage avec les autres."),
                ("Borrow", "Emprunter", "Borrow a book. - Emparunte un livre."),
                ("Lend", "Prêter", "Lend me your pen. - Prête-moi ton stylo."),
                ("Return", "Rendre", "Return the borrowed item. - Rends l'objet emprunté."),
            ]},
            {"title": "Finding & Searching", "words": [
                ("Find", "Trouver", "Find your keys. - Trouve tes clés."),
                ("Search", "Chercher", "Search online. - Cherche en ligne."),
                ("Look", "Regarder", "Look at me. - Regarde-moi."),
                ("See", "Voir", "See the view. - Vois le paysage."),
                ("Watch", "Regarder", "Watch a movie. - Regarde un film."),
                ("Discover", "Découvrir", "Discover new places. - Découvre de nouveaux endroits."),
            ]},
            {"title": "Planning", "words": [
                ("Plan", "Planifier", "Plan your future. - Planifie ton avenir."),
                ("Decide", "Décider", "Decide now. - Décide maintenant."),
                ("Choose", "Choisir", "Choose wisely. - Choisis judicieusement."),
                ("Prepare", "Préparer", "Prepare for the test. - Prépare-toi pour l'examen."),
                ("Organize", "Organiser", "Organize your room. - Organise ta chambre."),
                ("Schedule", "Planifier", "Schedule a meeting. - Planifie une réunion."),
            ]},
            {"title": "Relationships", "words": [
                ("Meet", "Rencontrer", "Meet new friends. - Rencontre de nouveaux amis."),
                ("Call", "Appeler", "Call me tonight. - Appelle-moi ce soir."),
                ("Invite", "Inviter", "Invite me to the party. - Invite-moi à la fête."),
                ("Join", "Rejoindre", "Join the team. - Rejoins l'équipe."),
                ("Welcome", "Bienvenue", "Welcome home! - Bienvenue à la maison!"),
                ("Marry", "Marier", "Marry the love of your life. - Marie-toi avec l'amour de ta vie."),
            ]},
            {"title": "Body Actions", "words": [
                ("Sit", "S'asseoir", "Sit down here. - Assieds-toi ici."),
                ("Stand", "Se lever", "Stand up please. - Lève-toi s'il te plaît."),
                ("Lie", "S'allonger", "Lie on the bed. - Allonge-toi sur le lit."),
                ("Lean", "S'appuyer", "Lean against the wall. - Appuie-toi contre le mur."),
                ("Stretch", "S'étirer", "Stretch your muscles. - Étire tes muscles."),
                ("Kneel", "S'agenouiller", "Kneel in prayer. - Agenouille-toi en prière."),
            ]},
            {"title": "Control", "words": [
                ("Open", "Ouvrir", "Open the door. - Ouvre la porte."),
                ("Close", "Fermer", "Close your eyes. - Ferme tes yeux."),
                ("Turn", "Tourner", "Turn the knob. - Tourne la poignée."),
                ("Push", "Pousser", "Push the button. - Pousse le bouton."),
                ("Pull", "Tirer", "Pull the lever. - Tire le levier."),
                ("Press", "Appuyer", "Press the key. - Appuie sur la touche."),
            ]},
            {"title": "Maintenance", "words": [
                ("Clean", "Nettoyer", "Clean your room. - Nettoie ta chambre."),
                ("Wash", "Laver", "Wash your hands. - Lave-toi les mains."),
                ("Fix", "Réparer", "Fix the bike. - Répare le vélo."),
                ("Repair", "Réparer", "Repair the broken item. - Répare l'objet cassé."),
                ("Paint", "Peindre", "Paint over the stain. - Peins par-dessus la tache."),
                ("Replace", "Remplacer", "Replace the battery. - Remplace la batterie."),
            ]},
            {"title": "Success & Failure", "words": [
                ("Win", "Gagner", "Win the game. - Gagne le jeu."),
                ("Lose", "Perdre", "Don't lose hope. - Ne perds pas espoir."),
                ("Succeed", "Réussir", "Succeed in life. - Réussis dans la vie."),
                ("Fail", "Échouer", "It's okay to fail. - C'est normal d'échouer."),
                ("Achieve", "Accomplir", "Achieve your goals. - Accomplis tes objectifs."),
                ("Try", "Essayer", "Try your best. - Fais de ton mieux."),
            ]},
            {"title": "Music & Art Verbs", "words": [
                ("Sing", "Chanter", "Sing along with me. - Chante avec moi."),
                ("Play", "Jouer", "Play an instrument. - Joue d'un instrument."),
                ("Dance", "Danser", "Dance at the party. - Danse à la fête."),
                ("Listen", "Écouter", "Listen to music. - Écoute de la musique."),
                ("Draw", "Dessiner", "Draw what you feel. - Dessine ce que tu ressens."),
                ("Photograph", "Photographier", "Photograph the sunset. - Photographier le coucher de soleil."),
            ]},
            {"title": "Nature Verbs", "words": [
                ("Grow", "Pousser", "Plants grow in sunlight. - Les plantes poussent à la lumière."),
                ("Bloom", "Fleurir", "Flowers bloom in spring. - Les fleurs fleurissent au printemps."),
                ("Rain", "Pleuvoir", "It rains cats and dogs. - Il pleut des cordes."),
                ("Snow", "Neiger", "It snowed last night. - Il a neigé cette nuit."),
                ("Shine", "Briller", "The sun shines bright. - Le soleil brille."),
                ("Sparkle", "Scintiller", "Stars sparkle at night. - Les étoiles scintillent la nuit."),
            ]},
            {"title": "Technology Verbs", "words": [
                ("Download", "Télécharger", "Download the file. - Télécharge le fichier."),
                ("Upload", "Téléverser", "Upload your photo. - Téléverse ta photo."),
                ("Click", "Cliquer", "Click the link. - Clique sur le lien."),
                ("Stream", "Diffuser", "Stream live video. - Diffuse en direct."),
                ("Post", "Publier", "Post on social media. - Publie sur les réseaux sociaux."),
                ("Chat", "Discuter", "Chat with friends. - Discute avec les amis."),
            ]},
            {"title": "Sports Verbs", "words": [
                ("Score", "Marquer", "Score a goal. - Marque un but."),
                ("Kick", "Donner un coup de pied", "Kick the ball. - Donne un coup de pied dans le ballon."),
                ("Throw", "Lancer", "Throw the ball. - Lance le ballon."),
                ("Catch", "Attraper", "Catch the ball. - Attrape le ballon."),
                ("Hit", "Frapper", "Hit the ball. - Frappe la balle."),
                ("Win", "Gagner", "Win the championship. - Gagne le championnat."),
            ]},
            {"title": "Daily Routine", "words": [
                ("Wake up", "Se réveiller", "Wake up early. - Réveille-toi tôt."),
                ("Get dressed", "S'habiller", "Get dressed quickly. - Habille-toi vite."),
                ("Brush teeth", "Se brosser les dents", "Brush your teeth twice. - Brosse-toi les dents deux fois."),
                ("Shower", "Se doucher", "Take a shower. - Prends une douche."),
                ("Leave home", "Partir de la maison", "Leave home at eight. - Pars de la maison à huit heures."),
                ("Come home", "Rentrer à la maison", "Come home from school. - Rentre de l'école."),
            ]},
            {"title": "Weather Verbs", "words": [
                ("Rain", "Pleuvoir", "It's raining outside. - Il pleut dehors."),
                ("Snow", "Neiger", "It's snowing heavily. - Il neige fort."),
                ("Storm", "Tempêter", "It storming last night. - Il a tempêté cette nuit."),
                ("Thunder", "Tonner", "It's thundering. - Ça tonne."),
                ("Flood", "Inonder", "The river flooded. - La rivière a inondé."),
                ("Gust", "Gonfler", "The wind gusted strongly. - Le vent a gonflé fortement."),
            ]},
        ]
    },
    # Category 8: Clothing & Fashion (Cards 161-175, 15 cards)
    {
        "name": "Clothing & Fashion",
        "cards": [
            {"title": "Tops", "words": [
                ("Shirt", "Chemise", "Wear a clean shirt. - Porte une chemise propre."),
                ("T-shirt", "T-shirt", "Cotton t-shirt. - T-shirt en coton."),
                ("Blouse", "Blouse", "Silk blouse. - Blouse en soie."),
                ("Sweater", "Chandail", "Wool sweater. - Chandail en laine."),
                ("Jacket", "Veste", "Leather jacket. - Veste en cuir."),
                ("Coat", "Manteau", "Winter coat. - Manteau d'hiver."),
            ]},
            {"title": "Bottoms", "words": [
                ("Pants", "Pantalon", "Blue jeans pants. - Pantalon bleu jeans."),
                ("Shorts", "Short", "Beach shorts. - Short de plage."),
                ("Skirt", "Jupe", "Pleated skirt. - Jupe plissée."),
                ("Jeans", "Jeans", "Ripped jeans style. - Style jeans déchirés."),
                ("Trousers", "Pantalons", "Dress trousers. - Pantalons habillés."),
                ("Leggings", "Leggings", "Athletic leggings. - Leggings de sport."),
            ]},
            {"title": "Footwear", "words": [
                ("Shoes", "Chaussures", "New shoes please. - Nouvelles chaussures s'il vous plaît."),
                ("Sneakers", "Basket", "Running sneakers. - Basket de course."),
                ("Boots", "Bottes", "Leather boots. - Bottes en cuir."),
                ("Sandals", "Sandales", "Summer sandals. - Sandales d'été."),
                ("Heels", "Talons", "High heels. - Talons hauts."),
                ("Slippers", "Pantoufles", "Cozy slippers. - Pantoufles confortables."),
            ]},
            {"title": "Accessories", "words": [
                ("Hat", "Chapeau", "Sun hat for beach. - Chapeau de soleil pour la plage."),
                ("Cap", "Casquette", "Baseball cap. - Casquette de baseball."),
                ("Scarf", "Écharpe", "Wool scarf. - Écharpe en laine."),
                ("Gloves", "Gants", "Winter gloves. - Gants d'hiver."),
                ("Belt", "Ceinture", "Leather belt. - Ceinture en cuir."),
                ("Tie", "Cravate", "Business tie. - Cravate de bureau."),
            ]},
            {"title": "Jewelry", "words": [
                ("Ring", "Bague", "Diamond ring. - Bague en diamant."),
                ("Necklace", "Collier", "Gold necklace. - Collier en or."),
                ("Bracelet", "Bracelet", "Silver bracelet. - Bracelet en argent."),
                ("Earrings", "Boucles d'oreilles", "Pearl earrings. - Boucles d'oreilles en perle."),
                ("Watch", "Montre", "Smart watch. - Montre connectée."),
                ("Brooch", "Broche", "Vintage brooch. - Broche vintage."),
            ]},
            {"title": "Bags", "words": [
                ("Backpack", "Sac à dos", "School backpack. - Sac à dos d'école."),
                ("Handbag", "Sac à main", "Designer handbag. - Sac à main de créateur."),
                ("Wallet", "Portefeuille", "Leather wallet. - Portefeuille en cuir."),
                ("Purse", "Sacoche", "Shoulder purse. - Sacoche d'épaule."),
                ("Suitcase", "Valise", "Pack the suitcase. - Fais la valise."),
                ("Briefcase", "Mallette", "Work briefcase. - Mallette de travail."),
            ]},
            {"title": "Sportswear", "words": [
                ("Jersey", "Maillot", "Team jersey. - Maillot d'équipe."),
                ("Uniform", "Uniforme", "School uniform. - Uniforme scolaire."),
                ("Tracksuit", "Costume de sport", "Nylon tracksuit. - Costume de sport en nylon."),
                ("Swimsuit", "Maillot de bain", "New swimsuit for summer. - Nouveau maillot de bain pour l'été."),
                ("Athletic wear", "Vêtements de sport", "Compression athletic wear. - Vêtements de sport de compression."),
                ("Socks", "Chaussettes", "Ankle socks. - Chaussettes de chevilles."),
            ]},
            {"title": "Sleepwear", "words": [
                ("Pajamas", "Pyjama", "Cozy pajamas. - Pyjama confortable."),
                ("Nightgown", "Chemise de nuit", "Long nightgown. - Chemise de nuit longue."),
                ("Robe", "Peignoir", "Bathrobe after shower. - Peignoir après la douche."),
                ("Loungewear", "Tenues de détente", "Comfortable loungewear. - Tenues de détente confortables."),
                ("Slippers", "Pantoufles", "Warm bedroom slippers. - Pantoufles chaudes de chambre."),
                ("Eye mask", "Masque de sommeil", "Silk eye mask. - Masque de sommeil en soie."),
            ]},
            {"title": "Formal Wear", "words": [
                ("Suit", "Complet", "Black suit for formal. - Complet noir pour habillé."),
                ("Dress", "Robe", "Evening dress. - Robe du soir."),
                ("Tuxedo", "Tuxedo", "Gentleman's tuxedo. - Tuxedo pour monsieur."),
                ("Gown", "Robe de soirée", "Ball gown. - Robe de soirée de bal."),
                ("Bow tie", "Noeud papillon", "Classic bow tie. - Noeud papillon classique."),
                ("Cummerbund", "Ceinture de smoking", "Silk cummerbund. - Ceinture de smoking en soie."),
            ]},
            {"title": "Weather Gear", "words": [
                ("Raincoat", "Imperméable", "Yellow raincoat. - Imperméable jaune."),
                ("Umbrella", "Parapluie", "Open the umbrella. - Ouvre le parapluie."),
                ("Poncho", "Poncho", "Mexican poncho. - Poncho mexicain."),
                ("Overalls", "Salopette", "Denim overalls. - Salopette en jean."),
                ("Parka", "Parka", "Winter parka with hood. - Parka d'hiver avec capuche."),
                ("Windbreaker", "Coupe-vent", "Light windbreaker. - Coupe-vent léger."),
            ]},
            {"title": "Fabrics", "words": [
                ("Cotton", "Coton", "100% cotton shirt. - Chemise 100% coton."),
                ("Silk", "Soie", "Smooth silk fabric. - Tissu de soie lisse."),
                ("Wool", "Laine", "Warm wool sweater. - Chandail de laine chaud."),
                ("Leather", "Cuir", "Genuine leather jacket. - Veste en cuir véritable."),
                ("Denim", "Denim", "Denim jeans material. - Matière denim pour jeans."),
                ("Linen", "Lin", "Breathable linen shirt. - Chemise en lin respirant."),
            ]},
            {"title": "Colors & Patterns", "words": [
                ("Striped", "Rayé", "Horizontal striped shirt. - Chemise à rayures horizontales."),
                ("Plaid", "À carreaux", "Classic plaid pattern. - Motif à carreaux classique."),
                ("Polka dot", "À pois", "Polka dot dress. - Robe à pois."),
                ("Floral", "Fleuri", "Floral print summer dress. - Robe d'été à motif floral."),
                ("Paisley", "Paisley", "Paisley tie pattern. - Motif de cravate paisley."),
                ("Argyle", "Argyles", "Argyle socks. - Chaussettes en argyles."),
            ]},
            {"title": "Sizes", "words": [
                ("Small", "Petit", "Small size fit. - Taille petit."),
                ("Medium", "Moyen", "Medium is just right. - Le moyen est juste bien."),
                ("Large", "Grand", "Large T-shirt. - Grand t-shirt."),
                ("Extra large", "Très grand", "Extra large XL. - Très grand XL."),
                ("Fitting", "Essayage", "Try it for fitting. - Essaie-le pour l'essayage."),
                ("Tailored", "Sur mesure", "Tailored suit fit. - Coupe de costume sur mesure."),
            ]},
            {"title": "Care Instructions", "words": [
                ("Wash", "Laver", "Machine wash cold. - Laver en machine à froid."),
                ("Dry clean", "Nettoyer à sec", "Dry clean only label. - Étiquette nettoyer à sec uniquement."),
                ("Iron", "Repasser", "Iron on medium heat. - Repasse à chaleur moyenne."),
                ("Bleach", "Javel", "Do not use bleach. - Ne pas utiliser de javel."),
                ("Tumble dry", "Sécher en machine", "Tumble dry low. - Sécher en machine à basse température."),
                ("Hang dry", "Sécher à l'air", "Hang dry recommended. - Séchage à l'air recommandé."),
            ]},
        ]
    },
    # Category 9: Transportation (Cards 176-190, 15 cards)
    {
        "name": "Transportation",
        "cards": [
            {"title": "Cars", "words": [
                ("Car", "Voiture", "Electric car new model. - Nouveau modèle de voiture électrique."),
                ("Sedan", "Berline", "Four door sedan. - Berline quatre portes."),
                ("SUV", "VUS", "Family SUV vehicle. - Véhicule VUS familial."),
                ("Truck", "Camion", "Pickup truck bed. - Benne de pickup truck."),
                ("Van", "Fourgonnette", "Passenger van rental. - Location de fourgonnette."),
                ("Convertible", "Décapotable", "Red convertible sports car. - Voiture de sport décapotable rouge."),
            ]},
            {"title": "Public Transport", "words": [
                ("Bus", "Autobus", "City bus route. - Route d'autobus urbain."),
                ("Subway", "Métro", "Take the subway. - Prends le métro."),
                ("Train", "Train", "High speed train. - Train à grande vitesse."),
                ("Tram", "Tramway", "Electric tram system. - Système de tramway électrique."),
                ("Taxi", "Taxi", "Call a taxi. - Appelle un taxi."),
                ("Rideshare", "Co-voiturage", "Rideshare app pickup. - Pickup via app de co-voiturage."),
            ]},
            {"title": "Air Travel", "words": [
                ("Airplane", "Avion", "Commercial airplane. - Avion commercial."),
                ("Airport", "Aéroport", "International airport terminal. - Terminal d'aéroport international."),
                ("Flight", "Vol", "Morning flight departure. - Départ de vol matinal."),
                ("Pilot", "Pilote", "Airline pilot. - Pilote de ligne."),
                ("Stewardess", "Hôtesse de l'air", "Flight attendant. - Hôtesse de l'air."),
                ("Luggage", "Bagages", "Checked luggage allowance. - Allocation de bagages enregistrés."),
            ]},
            {"title": "Bikes & Motorcycles", "words": [
                ("Bicycle", "Vélo", "Mountain bicycle. - Vélo de montagne."),
                ("Motorcycle", "Motocyclette", "Harley Davidson motorcycle. - Motocyclette Harley Davidson."),
                ("Scooter", "Scooter", "Electric scooter. - Scooter électrique."),
                ("Helmet", "Casque", "Safety helmet required. - Casque de sécurité requis."),
                ("Handlebar", "Guidon", "Adjustable handlebar. - Guidon ajustable."),
                ("Basket", "Panier", "Front bike basket. - Panier avant de vélo."),
            ]},
            {"title": "Road Terms", "words": [
                ("Highway", "Autoroute", "Speed on highway. - Vitesse sur autoroute."),
                ("Freeway", "Voie rapide", "Eight lane freeway. - Voie rapide à huit voies."),
                ("Intersection", "Intersection", "Busy intersection. - Intersection fréquentée."),
                ("Pedestrian", "Piéton", "Pedestrian crossing. - Passage pour piétons."),
                ("Traffic", "Circulation", "Heavy traffic jam. - Embouteillage lourd."),
                ("Speed limit", "Limite de vitesse", "Observe speed limit. - Observe la limite de vitesse."),
            ]},
            {"title": "Parts & Maintenance", "words": [
                ("Engine", "Moteur", "Engine check light. - Voyant de contrôle moteur."),
                ("Brake", "Frein", "Apply the brakes. - Applique les freins."),
                ("Tire", "Pneu", "Flat tire problem. - Problème de pneu à plat."),
                ("Battery", "Batterie", "Car battery dead. - Batterie de voiture à plat."),
                ("Mirror", "Rétroviseur", "Check the mirror. - Vérifie le rétroviseur."),
                ("Windshield", "Pare-brise", "Cracked windshield. - Pare-brise fissuré."),
            ]},
            {"title": "Train Travel", "words": [
                ("Station", "Gare", "Train station platform. - Quai de la gare."),
                ("Platform", "Quai", "Platform number seven. - Quai numéro sept."),
                ("Ticket", "Billet", "Round trip ticket. - Billet aller-retour."),
                ("Passenger", "Passager", "Train passenger car. - Voiture à passagers."),
                ("Schedule", "Horaire", "Train schedule changes. - Changements d'horaire de train."),
                ("Conductor", "Contrôleur", "Ticket from conductor. - Billet du contrôleur."),
            ]},
            {"title": "Boats & Ships", "words": [
                ("Boat", "Bateau", "Sailboat on lake. - Bateau à voile sur le lac."),
                ("Ship", "Navire", "Cruise ship size. - Taille du navire de croisière."),
                ("Yacht", "Yacht", "Luxury yacht. - Yacht de luxe."),
                ("Ferry", "Traversier", "Car ferry service. - Service de traversier pour autos."),
                ("Dock", "Quai", "Dock the boat. - Accoste le bateau."),
                ("Captain", "Capitaine", "Ship captain command. - Commande du capitaine de navire."),
            ]},
            {"title": "Travel Actions", "words": [
                ("Travel", "Voyager", "Travel abroad often. - Voyage souvent à l'étranger."),
                ("Commute", "Faire la navette", "Commute to work daily. - Faire la navette au travail quotidiennement."),
                ("Depart", "Partir", "Depart on time. - Partez à l'heure."),
                ("Arrive", "Arriver", "Arrive at destination. - Arriver à destination."),
                ("Transfer", "Correspondre", "Transfer at hub airport. - Correspondre à l'aéroport hub."),
                ("Delay", "Retarder", "Flight delay announced. - Retard de vol annoncé."),
            ]},
            {"title": "Navigation", "words": [
                ("Map", "Carte", "GPS map navigation. - Navigation par carte GPS."),
                ("GPS", "GPS", "Update GPS coordinates. - Mets à jour les coordonnées GPS."),
                ("Directions", "Directions", "Follow directions carefully. - Suis les directions attentivement."),
                ("Turn", "Tourner", "Turn left here. - Tourne ici à gauche."),
                ("U-turn", "Demi-tour", "Make a U-turn. - Fais un demi-tour."),
                ("Detour", "Détour", "Take a detour route. - Prends un itinéraire de détour."),
            ]},
            {"title": "Tickets & Fares", "words": [
                ("Fare", "Tarif", "Monthly pass fare. - Tarif de pass mensuel."),
                ("Pass", "Passe", "Unlimited ride pass. - Passe de trajets illimités."),
                ("Reservation", "Réservation", "Train seat reservation. - Réservation de siège train."),
                ("Seat", "Siège", "Window seat please. - Siège côté fenêtre s'il vous plaît."),
                ("Boarding pass", "Carte d'embarquement", "Scan boarding pass. - Scan de la carte d'embarquement."),
                ("Checkpoint", "Point de contrôle", "Security checkpoint line. - File du point de contrôle sécurité."),
            ]},
            {"title": "Driver Terms", "words": [
                ("Drive", "Conduire", "Learn to drive. - Apprendre à conduire."),
                ("Steer", "Diriger", "Steer the vehicle. - Dirige le véhicule."),
                ("Accelerate", "Accélérer", "Accelerate smoothly. - Accélère en douceur."),
                ("Brake", "Freiner", "Brake gradually here. - Freine progressivement ici."),
                ("Park", "Stationner", "Park the car here. - Stationne la voiture ici."),
                ("Reverse", "Reculer", "Reverse into the spot. - Recule dans la place."),
            ]},
            {"title": "Emergency Vehicles", "words": [
                ("Ambulance", "Ambulance", "Ambulance emergency sirens. - Sirènes d'urgence d'ambulance."),
                ("Fire truck", "Camion de pompier", "Fire truck response. - Intervention du camion de pompier."),
                ("Police car", "Voiture de police", "Police car pursuit. - Poursuite de voiture de police."),
                ("Siren", "Sirène", "Loud ambulance siren. - Forte sirène d'ambulance."),
                ("Emergency", "Urgence", "Call emergency services. - Appelle les services d'urgence."),
                ("Tow truck", "Dépanneuse", "Call the tow truck. - Appelle la dépanneuse."),
            ]},
            {"title": "Shipping & Cargo", "words": [
                ("Cargo", "Cargo", "Cargo ship containers. - Conteneurs de cargo."),
                ("Container", "Conteneur", "Shipping container yard. - Cour de conteneurs d'expédition."),
                ("Freight", "Fret", "Freight train service. - Service de train de fret."),
                ("Delivery", "Livraison", "Package delivery truck. - Camion de livraison de colis."),
                ("Warehouse", "Entrepôt", "Large warehouse storage. - Grand stockage d'entrepôt."),
                ("Cargo plane", "Avion cargo", "International cargo plane. - Avion cargo international."),
            ]},
        ]
    },
]

# Generate all cards
all_cards = []

# Cards 1-50 already exist, so we start from 51
card_number = 51

for category in vocab_categories:
    for card_template in category["cards"]:
        card_id = f"w{card_number:05d}"
        card = {
            "id": card_id,
            "title": card_template["title"],
            "day": card_number,
            "words": []
        }
        for i, (english, french, example) in enumerate(card_template["words"], 1):
            card["words"].append({
                "id": i,
                "english": english,
                "french": french,
                "example": example
            })
        all_cards.append(card)
        card_number += 1

# Generate JSON files
for card in all_cards:
    with open(f"src/lib/data/{card['id']}.json", "w") as f:
        json.dump(card, f, indent=2, ensure_ascii=False)
    f.close()

# Generate words.md
with open("words.md", "w", encoding="utf-8") as f:
    f.write("# Vocabulary List\n\n")
    f.write("| Word | Group | # |\n")
    f.write("|------|-------|---|\n")
    
    card_number = 51
    for category in vocab_categories:
        group_name = category["name"]
        for card_template in category["cards"]:
            for english, french, _ in card_template["words"]:
                f.write(f"| {english} | {group_name} | {card_number} |\n")
            card_number += 1

print(f"Generated {len(all_cards)} vocabulary cards (cards 51-{card_number-1})")
print("words.md created with complete vocabulary list")
